// app/state/TopicsContext.tsx
import React, { createContext, useContext, useMemo, useState } from "react";

// Generated by scripts/build_flashcard_index.mjs
const TOPICS_JSON = require("../_data/flashcard_topics.json");
// Optional: full index if you want groups/counts later
// const INDEX_JSON = require("../_data/flashcard_index.json");

type TopicsCtx = {
  topics: string[];
  selectedTopic: string | null;
  setSelectedTopic: (t: string | null) => void;
};

const Ctx = createContext<TopicsCtx | null>(null);

export function TopicsProvider({ children }: { children: React.ReactNode }) {
  const topics: string[] = Array.isArray(TOPICS_JSON?.topics) ? TOPICS_JSON.topics : [];
  const [selectedTopic, setSelectedTopic] = useState<string | null>(topics[0] || null);

  const value = useMemo(
    () => ({ topics, selectedTopic, setSelectedTopic }),
    [topics, selectedTopic]
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function useTopics() {
  const v = useContext(Ctx);
  if (!v) throw new Error("useTopics must be used inside <TopicsProvider>");
  return v;
}
