require('dotenv').config()
const express=require('express')
const cors=require('cors')
const bodyParser=require('body-parser')
const auth=require('./auth')
const app=express()
app.use(cors())
app.use(bodyParser.json())
app.use('/auth',auth)
app.get('/health',(req,res)=>res.json({ok:true}))
const port=Number(process.env.PORT||4000)
app.listen(port,()=>{})
