import { Topic } from "./topics";

export const MORE_TOPICS: any[] = [
  {
    id: "astronomy",
    title: "Astronomy",
    questions: [
      { q: "Closest star to Earth?", a: "The Sun" },
      { q: "Our galaxy’s name?", a: "The Milky Way" },
      { q: "Red Planet?", a: "Mars" },
      { q: "Largest planet in the solar system?", a: "Jupiter" },
      { q: "Moon phase fully lit?", a: "Full Moon" },
      { q: "Star type of the Sun?", a: "Yellow dwarf" },
      { q: "Exploding star term?", a: "Supernova" },
      { q: "Smallest planet in the solar system?", a: "Mercury" },
      { q: "Planet with the most moons (as of now)?", a: "Saturn" },
      {
        q: "What is a black hole?",
        a: "A region where gravity prevents light escaping",
      },
      { q: "Comets are mostly made of?", a: "Ice and dust" },
      { q: "Region beyond Neptune with icy bodies?", a: "Kuiper Belt" },
      { q: "Hottest planet in the solar system?", a: "Venus" },
      { q: "Name of our central black hole?", a: "Sagittarius A*" },
      { q: "Saturn’s rings are made of?", a: "Ice and rock" },
      { q: "Term for star brightness?", a: "Luminosity" },
      {
        q: "Cause of Northern Lights?",
        a: "Solar wind hitting the atmosphere",
      },
      { q: "What is a light-year?", a: "Distance light travels in a year" },
      { q: "Planet tilted on its side?", a: "Uranus" },
      { q: "Largest type of star?", a: "Supergiant" },
    ],
  },
  {
    id: "biology_fundamentals",
    title: "Biology Fundamentals",
    questions: [
      { q: "Basic unit of life?", a: "Cell" },
      { q: "Powerhouse of the cell?", a: "Mitochondrion" },
      { q: "Molecule carrying genetic info?", a: "DNA" },
      { q: "Plant food-making process?", a: "Photosynthesis" },
      { q: "Green pigment in plants?", a: "Chlorophyll" },
      { q: "Where proteins are made?", a: "Ribosomes" },
      { q: "Protein building blocks?", a: "Amino acids" },
      { q: "Quick energy macromolecule?", a: "Carbohydrates" },
      { q: "Internal balance term?", a: "Homeostasis" },
      { q: "Diffusion of water name?", a: "Osmosis" },
      { q: "Main cell membrane structure?", a: "Phospholipid bilayer" },
      { q: "Purpose of meiosis?", a: "Produce gametes" },
      { q: "Human somatic cell chromosomes?", a: "46" },
      { q: "Observable traits term?", a: "Phenotype" },
      { q: "Father of genetics?", a: "Gregor Mendel" },
      { q: "Bonds between DNA bases?", a: "Hydrogen bonds" },
      { q: "Central dogma?", a: "DNA → RNA → Protein" },
      { q: "Enzyme that unzips DNA?", a: "Helicase" },
      { q: "One-nucleotide change?", a: "Point mutation" },
      { q: "Community + environment?", a: "Ecosystem" },
    ],
  },
  {
    id: "chemistry",
    title: "Chemistry",
    questions: [
      { q: "Smallest unit of an element?", a: "Atom" },
      { q: "Nucleus contains?", a: "Protons and neutrons" },
      { q: "Avogadro’s number (approx)?", a: "6.022×10^23" },
      { q: "pH 7 is?", a: "Neutral" },
      { q: "Bond sharing electrons?", a: "Covalent bond" },
      { q: "NaCl common name?", a: "Table salt" },
      { q: "Electron charge?", a: "Negative" },
      { q: "Solid to gas directly?", a: "Sublimation" },
      { q: "PV constant at constant T law?", a: "Boyle’s law" },
      { q: "Molar mass of water?", a: "≈ 18 g/mol" },
      { q: "Arrhenius acid produces?", a: "H+ in water" },
      { q: "Oxidation is?", a: "Loss of electrons" },
      { q: "Reduction is?", a: "Gain of electrons" },
      { q: "Catalyst effect?", a: "Lowers activation energy" },
      { q: "Symbol K stands for?", a: "Potassium" },
      { q: "Strongest common IMF?", a: "Hydrogen bonding" },
      { q: "Ideal gas constant R (L·atm/mol·K)?", a: "0.0821" },
      { q: "Uniform mixture term?", a: "Solution" },
      { q: "Electron-pair geometry of CH4?", a: "Tetrahedral" },
      { q: "pH of 1×10^-3 M H+?", a: "3" },
    ],
  },
  {
    id: "physics",
    title: "Physics",
    questions: [
      { q: "SI unit of force?", a: "Newton" },
      { q: "Gravity near Earth (m/s^2)?", a: "≈ 9.8" },
      { q: "Newton’s First Law aka?", a: "Law of inertia" },
      { q: "Work equals force times?", a: "Displacement" },
      { q: "Kinetic energy formula?", a: "1/2 mv^2" },
      { q: "Momentum equals?", a: "Mass × velocity" },
      { q: "Ohm’s law?", a: "V = IR" },
      { q: "Speed of light (m/s)?", a: "≈ 3.0×10^8" },
      { q: "Cycles per second term?", a: "Frequency" },
      { q: "SI unit of charge?", a: "Coulomb" },
      { q: "Power in mechanics is?", a: "Work per unit time" },
      { q: "Refraction cause?", a: "Speed change in media" },
      { q: "Entropy measures?", a: "Disorder" },
      { q: "Strong force acts on?", a: "Hadrons (protons/neutrons)" },
      { q: "Hooke’s law?", a: "F = -kx" },
      { q: "Doppler effect?", a: "Frequency shift from motion" },
      { q: "Conserved in isolated collisions?", a: "Momentum" },
      { q: "SI unit of energy?", a: "Joule" },
      { q: "EM force carrier?", a: "Photon" },
      { q: "Lens that converges light?", a: "Convex" },
    ],
  },
  {
    id: "algebra",
    title: "Algebra",
    questions: [
      { q: "Solve 2x+6=14", a: "x=4" },
      { q: "Factor x^2-9", a: "(x-3)(x+3)" },
      { q: "In y=mx+b, m is?", a: "Slope" },
      { q: "Solve 3(x-2)=9", a: "x=5" },
      { q: "Expand (x+2)(x+5)", a: "x^2+7x+10" },
      { q: "Vertex of y=(x-4)^2", a: "(4,0)" },
      { q: "x/3=7 → x?", a: "21" },
      { q: "Factor x^2+5x+6", a: "(x+2)(x+3)" },
      { q: "5x-2=3x+10 → x?", a: "x=6" },
      { q: "y-intercept of y=2x-8", a: "-8" },
      { q: "(x^3)(x^2) =", a: "x^5" },
      { q: "|x-4|=2 → x?", a: "x=6 or x=2" },
      { q: "Factor 2x^2-8x", a: "2x(x-4)" },
      { q: "x^2=49 → x?", a: "±7" },
      { q: "m=3, b=-2 → line?", a: "y=3x-2" },
      { q: "Solve x+y=6, x-y=2", a: "x=4, y=2" },
      { q: "(2x^2)^3 =", a: "8x^6" },
      { q: "Slope between (1,2),(5,6)", a: "1" },
      { q: "4^x=16 → x?", a: "2" },
      { q: "Factor x^2-4x+4", a: "(x-2)^2" },
    ],
  },
  {
    id: "geometry",
    title: "Geometry",
    questions: [
      { q: "Sum of angles in a triangle?", a: "180°" },
      { q: "Right triangle has angle of?", a: "90°" },
      { q: "Circumference formula?", a: "C=2πr" },
      { q: "Area of circle?", a: "A=πr^2" },
      { q: "Pythagorean theorem?", a: "a^2+b^2=c^2" },
      { q: "Parallelogram opposite sides are?", a: "Parallel and equal" },
      { q: "Polygon with 5 sides?", a: "Pentagon" },
      { q: "Interior angle sum of quadrilateral?", a: "360°" },
      {
        q: "Median of a triangle connects?",
        a: "Vertex to midpoint of opposite side",
      },
      { q: "Radius is half the?", a: "Diameter" },
      { q: "Area of triangle?", a: "A=1/2 bh" },
      { q: "Regular polygon sides and angles are?", a: "Equal" },
      { q: "A line with zero slope is?", a: "Horizontal" },
      { q: "Slope of vertical line?", a: "Undefined" },
      { q: "Similar figures have same?", a: "Shape (proportional sides)" },
      { q: "Congruent figures are?", a: "Same shape and size" },
      { q: "Parallel lines symbol?", a: "∥" },
      { q: "Perpendicular lines symbol?", a: "⟂" },
      {
        q: "Exterior angle of triangle equals?",
        a: "Sum of two remote interior angles",
      },
      { q: "Number of diagonals in pentagon?", a: "5" },
    ],
  },
  {
    id: "calculus",
    title: "Calculus",
    questions: [
      { q: "Derivative of x^2?", a: "2x" },
      { q: "Derivative of sin x?", a: "cos x" },
      { q: "Integral of 1/x dx?", a: "ln|x|+C" },
      {
        q: "Fundamental Theorem connects?",
        a: "Differentiation and integration",
      },
      { q: "d/dx (e^x)?", a: "e^x" },
      { q: "∫ cos x dx?", a: "sin x + C" },
      { q: "Chain rule is for?", a: "Derivative of composite functions" },
      { q: "Product rule formula?", a: "(fg)'=f'g+fg'" },
      { q: "Quotient rule formula?", a: "(f/g)'=(f'g - fg')/g^2" },
      { q: "Limit as x→0 of sin x / x?", a: "1" },
      { q: "Derivative gives?", a: "Instantaneous rate of change" },
      { q: "Integral gives?", a: "Accumulated area/quantity" },
      { q: "Critical point when?", a: "f'(x)=0 or undefined" },
      { q: "Concave up when?", a: "f''(x)>0" },
      { q: "Local max when?", a: "f' changes + to -" },
      {
        q: "Mean Value Theorem needs?",
        a: "Continuous on [a,b], differentiable (a,b)",
      },
      { q: "∫ 0→1 x dx?", a: "1/2" },
      { q: "d/dx (ln x)?", a: "1/x" },
      { q: "∫ e^x dx?", a: "e^x + C" },
      { q: "Derivative of c (const)?", a: "0" },
    ],
  },
  {
    id: "computer_science",
    title: "Computer Science",
    questions: [
      { q: "CPU stands for?", a: "Central Processing Unit" },
      { q: "Binary base?", a: "Base 2" },
      { q: "RAM stands for?", a: "Random Access Memory" },
      { q: "FIFO structure?", a: "Queue" },
      { q: "LIFO structure?", a: "Stack" },
      { q: "Binary search time?", a: "O(log n)" },
      { q: "In-place O(n log n) sort?", a: "Quicksort" },
      { q: "SQL stands for?", a: "Structured Query Language" },
      { q: "HTTP stands for?", a: "Hypertext Transfer Protocol" },
      { q: "Hash function property?", a: "Deterministic fixed-size map" },
      { q: "Recursion is?", a: "Function calls itself" },
      { q: "Algorithm is?", a: "Step-by-step procedure" },
      { q: "Key-value structure?", a: "Hash map / dictionary" },
      { q: "API stands for?", a: "Application Programming Interface" },
      { q: "OS purpose?", a: "Manage hardware & services" },
      { q: "Compiler does?", a: "Translates code to machine code" },
      { q: "Concurrency means?", a: "Tasks progress overlapping" },
      { q: "DB index?", a: "Speeds up retrieval" },
      { q: "Normalization?", a: "Reduce redundancy" },
      { q: "RESTful service?", a: "Follows REST constraints" },
    ],
  },
  {
    id: "world_history",
    title: "World History",
    questions: [
      { q: "Ancient Egypt river?", a: "Nile" },
      { q: "First Roman emperor?", a: "Augustus" },
      { q: "China–Mediterranean trade route?", a: "Silk Road" },
      { q: "Machu Picchu builders?", a: "Inca" },
      { q: "Berlin Wall fell in?", a: "1989" },
      { q: "India’s nonviolent leader?", a: "Mahatma Gandhi" },
      { q: "14th-century pandemic?", a: "Black Death" },
      { q: "Revolution starting 1789?", a: "French Revolution" },
      { q: "Posted Ninety-Five Theses?", a: "Martin Luther" },
      { q: "Empire of Genghis Khan?", a: "Mongol Empire" },
      { q: "Pilgrims’ ship 1620?", a: "Mayflower" },
      { q: "Victorian Era queen?", a: "Queen Victoria" },
      { q: "War from 1939 invasion of Poland?", a: "World War II" },
      { q: "Cold War was?", a: "US vs USSR tension" },
      { q: "Hagia Sophia first built by?", a: "Byzantine Empire" },
      { q: "Early legal code?", a: "Code of Hammurabi" },
      { q: "Trench war on Western Front?", a: "World War I" },
      { q: "Queen allied with Mark Antony?", a: "Cleopatra VII" },
      { q: "Started Reformation event?", a: "Posting the Theses" },
      { q: "Cuneiform creators?", a: "Sumerians" },
    ],
  },
  {
    id: "us_history",
    title: "U.S. History",
    questions: [
      { q: "Declaration year?", a: "1776" },
      { q: "First U.S. president?", a: "George Washington" },
      { q: "Civil War years?", a: "1861–1865" },
      { q: "Emancipation Proclamation by?", a: "Abraham Lincoln" },
      { q: "Great Depression decade?", a: "1930s" },
      { q: "New Deal president?", a: "Franklin D. Roosevelt" },
      { q: "Pearl Harbor date?", a: "Dec 7, 1941" },
      { q: "Civil Rights Act year?", a: "1964" },
      { q: "Moon landing year?", a: "1969" },
      { q: "Cold War rivals?", a: "U.S. and U.S.S.R." },
      { q: "Louisiana Purchase from?", a: "France" },
      { q: "13th Amendment effect?", a: "Abolished slavery" },
      { q: "Document framing government?", a: "Constitution" },
      { q: "First 10 amendments name?", a: "Bill of Rights" },
      { q: "War of 1812 opponent?", a: "Great Britain" },
      { q: "D-Day year?", a: "1944" },
      { q: "Brown v. Board year?", a: "1954" },
      { q: "Marshall Plan aided?", a: "Europe" },
      { q: "Watergate led to?", a: "Nixon’s resignation" },
      { q: "Alaska purchased from?", a: "Russia" },
    ],
  },
  {
    id: "geography",
    title: "Geography",
    questions: [
      { q: "Longest river (by many measures)?", a: "Nile" },
      { q: "Largest hot desert?", a: "Sahara" },
      { q: "Largest ocean?", a: "Pacific" },
      { q: "Everest borders which countries?", a: "Nepal and China" },
      { q: "Equator divides which hemispheres?", a: "North and South" },
      { q: "Capital of Japan?", a: "Tokyo" },
      { q: "Largest U.S. state by area?", a: "Alaska" },
      { q: "Continent with most countries?", a: "Africa" },
      { q: "Smallest country?", a: "Vatican City" },
      { q: "River through Paris?", a: "Seine" },
      { q: "Capital of Australia?", a: "Canberra" },
      { q: "Most populous country?", a: "India" },
      { q: "Deepest lake?", a: "Lake Baikal" },
      { q: "Andes on which side of S. America?", a: "West" },
      { q: "Istanbul spans which continents?", a: "Europe and Asia" },
      { q: "Capital of Canada?", a: "Ottawa" },
      { q: "River with delta in Nigeria?", a: "Niger River" },
      { q: "Sea between Europe and Africa?", a: "Mediterranean" },
      { q: "Largest island?", a: "Greenland" },
      { q: "U.S. river bordering Mexico?", a: "Rio Grande" },
    ],
  },
  {
    id: "economics",
    title: "Economics",
    questions: [
      { q: "Scarcity means?", a: "Limited resources vs unlimited wants" },
      { q: "Opportunity cost?", a: "Best forgone alternative" },
      { q: "Law of demand?", a: "Price↑ → quantity demanded↓" },
      { q: "Law of supply?", a: "Price↑ → quantity supplied↑" },
      { q: "Elastic demand reacts how?", a: "Strongly to price changes" },
      { q: "GDP measures?", a: "Final goods/services value" },
      { q: "Inflation is?", a: "General rise in prices" },
      { q: "Monetary policy tool?", a: "Interest rates" },
      { q: "Fiscal policy uses?", a: "Spending and taxes" },
      { q: "Comparative advantage is?", a: "Lower opportunity cost" },
      { q: "Equilibrium is?", a: "Qs = Qd" },
      { q: "Marginal benefit is?", a: "Extra benefit of one more" },
      { q: "Price ceiling effect risk?", a: "Shortages" },
      { q: "Price floor example?", a: "Minimum wage" },
      { q: "CPI tracks?", a: "Consumer price changes" },
      { q: "Real vs nominal GDP?", a: "Adjusted vs unadjusted for inflation" },
      { q: "Unemployment types?", a: "Frictional, structural, cyclical" },
      { q: "Public good trait?", a: "Non-rival, non-excludable" },
      { q: "Externality example?", a: "Pollution" },
      { q: "Trade-off means?", a: "Giving up one thing for another" },
    ],
  },
  {
    id: "climate_change",
    title: "Climate Change",
    questions: [
      { q: "Main human GHG?", a: "CO2" },
      { q: "Greenhouse effect does?", a: "Traps heat" },
      { q: "Primary CO2 source?", a: "Fossil fuel combustion" },
      { q: "Methane sources?", a: "Agriculture, energy, waste" },
      { q: "Ocean acidification cause?", a: "CO2 dissolving in seawater" },
      { q: "Mitigation example?", a: "Renewable energy" },
      { q: "Adaptation example?", a: "Sea walls" },
      { q: "IPCC stands for?", a: "Intergovernmental Panel on Climate Change" },
      { q: "Warming baseline is?", a: "Pre-industrial levels" },
      { q: "Feedback example?", a: "Ice–albedo feedback" },
      { q: "Carbon sink examples?", a: "Forests and oceans" },
      { q: "Net-zero means?", a: "Emissions balanced by removals" },
      { q: "Climate vs weather?", a: "Long-term vs short-term" },
      { q: "GHG with highest warming share?", a: "CO2" },
      { q: "N2O source?", a: "Agriculture (fertilizers)" },
      { q: "Black carbon effect?", a: "Atmospheric warming" },
      { q: "Paris Agreement goal?", a: "Limit warming well below 2°C" },
      { q: "Sea-level rise driver?", a: "Thermal expansion & ice melt" },
      { q: "Just transition means?", a: "Fair shift for workers/communities" },
      { q: "Carbon pricing tools?", a: "Taxes and cap-and-trade" },
    ],
  },
  {
    id: "literature",
    title: "Literature",
    questions: [
      { q: "Simile definition?", a: "Comparison using like/as" },
      { q: "Metaphor definition?", a: "Direct comparison without like/as" },
      { q: "Author of Romeo and Juliet?", a: "William Shakespeare" },
      { q: "Protagonist is?", a: "Main character" },
      { q: "Antagonist is?", a: "Opponent to the protagonist" },
      { q: "Foreshadowing is?", a: "Hints of future events" },
      { q: "Alliteration is?", a: "Repetition of initial sounds" },
      { q: "Author of 1984?", a: "George Orwell" },
      { q: "Hyperbole is?", a: "Exaggeration for effect" },
      { q: "Theme is?", a: "Central idea" },
      { q: "First-person uses?", a: "I" },
      { q: "Irony is?", a: "Expectation vs reality" },
      { q: "Sonnet lines?", a: "14" },
      { q: "Author of The Odyssey?", a: "Homer" },
      { q: "Stanza is?", a: "Grouped lines" },
      { q: "Personification is?", a: "Human traits to nonhuman" },
      { q: "Climax is?", a: "Turning point" },
      { q: "Symbol is?", a: "Object representing idea" },
      { q: "Onomatopoeia is?", a: "Word imitating sound" },
      { q: "Author of Pride and Prejudice?", a: "Jane Austen" },
    ],
  },
  {
    id: "grammar",
    title: "English Grammar",
    questions: [
      { q: "Noun is?", a: "Person, place, thing, idea" },
      { q: "Verb is?", a: "Action or state" },
      { q: "Adjective does?", a: "Describes a noun" },
      { q: "Adverb does?", a: "Modifies verb/adjective/adverb" },
      { q: "Pronoun is?", a: "Replaces a noun" },
      { q: "Subject-verb agreement?", a: "Singular with singular, etc." },
      { q: "Active voice example?", a: "The dog chased the cat." },
      { q: "Passive voice example?", a: "The cat was chased by the dog." },
      { q: "Comma splice is?", a: "Two clauses joined by comma only" },
      { q: "Oxford comma use?", a: "Before 'and' in lists" },
      { q: "Semicolon joins?", a: "Related independent clauses" },
      { q: "Clause vs phrase?", a: "Clause has subject and verb" },
      { q: "Gerund is?", a: "Verb acting as noun (-ing)" },
      { q: "Infinitive is?", a: "To + base verb" },
      { q: "Parallel structure?", a: "Same grammatical forms" },
      { q: "Dangling modifier?", a: "Modifier lacking a clear subject" },
      { q: "Apostrophe for possession?", a: "Add 's or s'" },
      { q: "Its vs it’s?", a: "Possessive vs contraction" },
      { q: "Who vs whom?", a: "Subject vs object" },
      { q: "Fewer vs less?", a: "Countable vs uncountable" },
    ],
  },
  {
    id: "art_history",
    title: "Art History",
    questions: [
      { q: "Mona Lisa painter?", a: "Leonardo da Vinci" },
      { q: "Starry Night painter?", a: "Vincent van Gogh" },
      { q: "Sistine Chapel ceiling artist?", a: "Michelangelo" },
      { q: "The Persistence of Memory artist?", a: "Salvador Dalí" },
      { q: "Cubism pioneers?", a: "Picasso and Braque" },
      { q: "Impressionism origin?", a: "19th-century France" },
      { q: "Fresco is?", a: "Painting on wet plaster" },
      { q: "Renaissance dates (approx)?", a: "14th–17th centuries" },
      { q: "Guernica theme?", a: "Anti-war" },
      { q: "The Thinker sculptor?", a: "Auguste Rodin" },
      { q: "Baroque style trait?", a: "Dramatic contrast and motion" },
      { q: "Surrealism goal?", a: "Unlock the unconscious" },
      { q: "MoMA stands for?", a: "Museum of Modern Art" },
      { q: "Impression, Sunrise painter?", a: "Claude Monet" },
      { q: "Pop Art icon?", a: "Andy Warhol" },
      { q: "Pointillism founder?", a: "Georges Seurat" },
      { q: "Girl with a Pearl Earring painter?", a: "Johannes Vermeer" },
      { q: "The Kiss painter?", a: "Gustav Klimt" },
      { q: "Mannerism follows?", a: "High Renaissance" },
      { q: "Fauvism hallmark?", a: "Bold color" },
    ],
  },
  {
    id: "music_theory",
    title: "Music Theory",
    questions: [
      { q: "Notes in a major scale?", a: "7 distinct notes" },
      { q: "Distance between pitches?", a: "Interval" },
      { q: "Symbol raising a note half step?", a: "Sharp (#)" },
      { q: "Symbol lowering half step?", a: "Flat (b)" },
      { q: "Italian for loud?", a: "Forte" },
      { q: "Italian for soft?", a: "Piano" },
      { q: "Relative minor of C major?", a: "A minor" },
      { q: "Semitones in an octave?", a: "12" },
      { q: "Key signature of G major?", a: "One sharp (F#)" },
      { q: "Term for speed?", a: "Tempo" },
      { q: "Allegro means?", a: "Fast" },
      { q: "Adagio means?", a: "Slow" },
      { q: "Strongest beat in 4/4?", a: "Beat 1" },
      { q: "1-3-5 chord name?", a: "Triad" },
      { q: "Clef used for violin?", a: "Treble" },
      { q: "Clef used for cello?", a: "Bass" },
      { q: "Harmony is?", a: "Simultaneous notes" },
      { q: "Melody is?", a: "Sequence of notes" },
      { q: "Crescendo means?", a: "Getting louder" },
      { q: "Diminuendo means?", a: "Getting softer" },
    ],
  },
  {
    id: "psychology",
    title: "Psychology",
    questions: [
      { q: "Father of psychoanalysis?", a: "Sigmund Freud" },
      { q: "Brain part for fear/emotion?", a: "Amygdala" },
      { q: "IQ stands for?", a: "Intelligence Quotient" },
      { q: "Cognitive dissonance?", a: "Discomfort from conflicting beliefs" },
      { q: "Hierarchy of needs by?", a: "Abraham Maslow" },
      { q: "Classical conditioning?", a: "Learning by association" },
      { q: "Little Albert experimenter?", a: "John B. Watson" },
      { q: "Operant conditioning?", a: "Learning via rewards & punishment" },
      { q: "Short-term memory also?", a: "Working memory" },
      { q: "Placebo effect?", a: "Improvement from inert treatment" },
      { q: "Confirmation bias?", a: "Favoring confirming info" },
      { q: "Conformity studies by?", a: "Solomon Asch" },
      { q: "PTSD stands for?", a: "Post-Traumatic Stress Disorder" },
      { q: "Phobia is?", a: "Irrational specific fear" },
      { q: "Study of dreams?", a: "Oneirology" },
      { q: "Intrinsic motivation?", a: "Internal satisfaction" },
      { q: "Extrinsic motivation?", a: "External rewards" },
      { q: "ADHD stands for?", a: "Attention Deficit Hyperactivity Disorder" },
      { q: "Fight-or-flight?", a: "Stress response" },
      { q: "Multiple intelligences by?", a: "Howard Gardner" },
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    questions: [
      { q: "4 Ps of marketing?", a: "Product, Price, Place, Promotion" },
      { q: "Market segmentation?", a: "Dividing market into groups" },
      { q: "Brand equity?", a: "Value from brand perception" },
      { q: "Positioning?", a: "Place in consumer’s mind" },
      { q: "USP stands for?", a: "Unique Selling Proposition" },
      {
        q: "Funnel stages (basic)?",
        a: "Awareness, Interest, Decision, Action",
      },
      { q: "CAC stands for?", a: "Customer Acquisition Cost" },
      { q: "LTV stands for?", a: "Lifetime Value" },
      { q: "A/B test purpose?", a: "Compare two variants" },
      { q: "Persona is?", a: "Semi-fictional user profile" },
      { q: "Churn rate?", a: "Customers lost over time" },
      { q: "NPS measures?", a: "Likelihood to recommend" },
      { q: "Organic traffic?", a: "Unpaid search traffic" },
      { q: "CTR stands for?", a: "Click-Through Rate" },
      { q: "CPC stands for?", a: "Cost Per Click" },
      { q: "SEO stands for?", a: "Search Engine Optimization" },
      { q: "Email open rate?", a: "Opens divided by sends" },
      { q: "Retargeting does?", a: "Ads to prior visitors" },
      { q: "Value proposition?", a: "Why choose your product" },
      { q: "Social proof?", a: "Influence from others’ actions" },
    ],
  },
  {
    id: "entrepreneurship",
    title: "Entrepreneurship",
    questions: [
      { q: "MVP stands for?", a: "Minimum Viable Product" },
      { q: "Lean startup focuses on?", a: "Build-Measure-Learn" },
      { q: "Bootstrapping means?", a: "Self-funding growth" },
      { q: "Runway is?", a: "Time left before cash out" },
      { q: "Burn rate?", a: "Cash spent per period" },
      { q: "Pivot means?", a: "Strategic change" },
      { q: "Moat is?", a: "Defensible advantage" },
      { q: "Cap table lists?", a: "Ownership/equity stakes" },
      { q: "Term sheet is?", a: "Proposed investment terms" },
      { q: "Dilution means?", a: "Ownership % decreases" },
      { q: "SAFE stands for?", a: "Simple Agreement for Future Equity" },
      { q: "ARR stands for?", a: "Annual Recurring Revenue" },
      { q: "Gross margin?", a: "Revenue − COGS" },
      { q: "Churn hurts what?", a: "Retention/revenue" },
      { q: "Unit economics?", a: "Profitability per unit" },
      { q: "North Star metric?", a: "Core value indicator" },
      { q: "Cohort analysis tracks?", a: "Groups over time" },
      { q: "Freemium means?", a: "Free tier + paid upgrades" },
      { q: "Network effects?", a: "Value grows with users" },
      { q: "Go-to-market plan?", a: "How to reach customers" },
    ],
  },
];
