import { Topic } from "./topics";

export const LANGUAGE_TOPICS: any[] = [
  {
    id: "spanish_basics",
    title: "Spanish Basics",
    questions: [
      { q: "Hello", a: "Hola" },
      { q: "Goodbye", a: "Adiós" },
      { q: "Please", a: "Por favor" },
      { q: "Thank you", a: "Gracias" },
      { q: "You’re welcome", a: "De nada" },
      { q: "Yes / No", a: "Sí / No" },
      { q: "Excuse me / Sorry", a: "Perdón / Lo siento" },
      { q: "What is your name?", a: "¿Cómo te llamas?" },
      { q: "My name is…", a: "Me llamo…" },
      { q: "How are you?", a: "¿Cómo estás?" },
      { q: "I’m fine", a: "Estoy bien" },
      { q: "I don’t understand", a: "No entiendo" },
      { q: "Do you speak English?", a: "¿Hablas inglés?" },
      { q: "Where is the bathroom?", a: "¿Dónde está el baño?" },
      { q: "How much is it?", a: "¿Cuánto cuesta?" },
      { q: "I would like…", a: "Me gustaría…" },
      { q: "Help!", a: "¡Ayuda!" },
      { q: "Numbers 1–5", a: "Uno, dos, tres, cuatro, cinco" },
      {
        q: "Days: Mon–Sun",
        a: "Lunes, martes, miércoles, jueves, viernes, sábado, domingo",
      },
      { q: "Colors: red/blue/green", a: "Rojo / azul / verde" },
    ],
  },
  {
    id: "french_basics",
    title: "French Basics",
    questions: [
      { q: "Hello / Good morning", a: "Bonjour" },
      { q: "Good evening / Good night", a: "Bonsoir / Bonne nuit" },
      { q: "Goodbye", a: "Au revoir" },
      { q: "Please / Thank you", a: "S’il vous plaît / Merci" },
      { q: "You’re welcome", a: "De rien" },
      { q: "Yes / No", a: "Oui / Non" },
      { q: "Excuse me / Sorry", a: "Excusez-moi / Désolé(e)" },
      { q: "What is your name?", a: "Comment vous appelez-vous ?" },
      { q: "My name is…", a: "Je m’appelle…" },
      { q: "How are you?", a: "Comment ça va ?" },
      { q: "I’m fine", a: "Ça va bien" },
      { q: "I don’t understand", a: "Je ne comprends pas" },
      { q: "Do you speak English?", a: "Parlez-vous anglais ?" },
      { q: "Where is the bathroom?", a: "Où sont les toilettes ?" },
      { q: "How much is it?", a: "C’est combien ?" },
      { q: "I would like…", a: "Je voudrais…" },
      { q: "Help!", a: "À l’aide !" },
      { q: "Numbers 1–5", a: "Un, deux, trois, quatre, cinq" },
      {
        q: "Days: Mon–Sun",
        a: "Lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche",
      },
      { q: "Colors: red/blue/green", a: "Rouge / bleu / vert" },
    ],
  },
  {
    id: "german_basics",
    title: "German Basics",
    questions: [
      { q: "Hello / Goodbye", a: "Hallo / Auf Wiedersehen" },
      { q: "Please / Thank you", a: "Bitte / Danke" },
      { q: "You’re welcome", a: "Gern geschehen" },
      { q: "Yes / No", a: "Ja / Nein" },
      { q: "Excuse me / Sorry", a: "Entschuldigung / Tut mir leid" },
      { q: "What is your name?", a: "Wie heißt du?" },
      { q: "My name is…", a: "Ich heiße…" },
      { q: "How are you?", a: "Wie geht’s?" },
      { q: "I’m fine", a: "Mir geht’s gut" },
      { q: "I don’t understand", a: "Ich verstehe nicht" },
      { q: "Do you speak English?", a: "Sprichst du Englisch?" },
      { q: "Where is the bathroom?", a: "Wo ist die Toilette?" },
      { q: "How much is it?", a: "Wie viel kostet das?" },
      { q: "I would like…", a: "Ich hätte gern…" },
      { q: "Help!", a: "Hilfe!" },
      { q: "Numbers 1–5", a: "Eins, zwei, drei, vier, fünf" },
      {
        q: "Days: Mon–Sun",
        a: "Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag, Sonntag",
      },
      { q: "Colors: red/blue/green", a: "Rot / blau / grün" },
      { q: "Good morning / night", a: "Guten Morgen / Gute Nacht" },
      { q: "Cheers!", a: "Prost!" },
    ],
  },
  {
    id: "italian_basics",
    title: "Italian Basics",
    questions: [
      { q: "Hello / Goodbye", a: "Ciao / Arrivederci" },
      { q: "Please / Thank you", a: "Per favore / Grazie" },
      { q: "You’re welcome", a: "Prego" },
      { q: "Yes / No", a: "Sì / No" },
      { q: "Excuse me / Sorry", a: "Scusi / Mi dispiace" },
      { q: "What is your name?", a: "Come ti chiami?" },
      { q: "My name is…", a: "Mi chiamo…" },
      { q: "How are you?", a: "Come stai?" },
      { q: "I’m fine", a: "Sto bene" },
      { q: "I don’t understand", a: "Non capisco" },
      { q: "Do you speak English?", a: "Parli inglese?" },
      { q: "Where is the bathroom?", a: "Dov’è il bagno?" },
      { q: "How much is it?", a: "Quanto costa?" },
      { q: "I would like…", a: "Vorrei…" },
      { q: "Help!", a: "Aiuto!" },
      { q: "Numbers 1–5", a: "Uno, due, tre, quattro, cinque" },
      {
        q: "Days: Mon–Sun",
        a: "Lunedì, martedì, mercoledì, giovedì, venerdì, sabato, domenica",
      },
      { q: "Colors: red/blue/green", a: "Rosso / blu / verde" },
      { q: "Good morning / night", a: "Buongiorno / Buonanotte" },
      { q: "Where are you from?", a: "Di dove sei?" },
    ],
  },
  {
    id: "japanese_romaji",
    title: "Japanese (Romaji)",
    questions: [
      { q: "Hello / Goodbye", a: "Konnichiwa / Sayōnara" },
      { q: "Please / Thank you", a: "Onegai shimasu / Arigatō" },
      { q: "Yes / No", a: "Hai / Iie" },
      { q: "Excuse me / Sorry", a: "Sumimasen / Gomen nasai" },
      { q: "What is your name?", a: "Onamae wa?" },
      { q: "My name is…", a: "Watashi no namae wa … desu" },
      { q: "How are you?", a: "Ogenki desu ka?" },
      { q: "I’m fine", a: "Genki desu" },
      { q: "I don’t understand", a: "Wakarimasen" },
      { q: "Do you speak English?", a: "Eigo o hanasemasu ka?" },
      { q: "Where is the bathroom?", a: "Toire wa doko desu ka?" },
      { q: "How much is it?", a: "Ikura desu ka?" },
      { q: "I would like…", a: "… o onegai shimasu" },
      { q: "Help!", a: "Tasukete!" },
      { q: "Numbers 1–5", a: "Ichi, ni, san, shi/yon, go" },
      { q: "Days: Mon–Sun", a: "Getsu, Ka, Sui, Moku, Kin, Do, Nichi" },
      { q: "Colors: red/blue/green", a: "Aka / ao / midori" },
      { q: "Good morning / night", a: "Ohayō / Oyasumi" },
      { q: "Delicious", a: "Oishii" },
      { q: "Where are you from?", a: "Doko kara kimashita ka?" },
    ],
  },
  {
    id: "mandarin_pinyin",
    title: "Mandarin Chinese (Pinyin)",
    questions: [
      { q: "Hello", a: "Nǐ hǎo" },
      { q: "Goodbye", a: "Zàijiàn" },
      { q: "Please / Thank you", a: "Qǐng / Xièxie" },
      { q: "You’re welcome", a: "Bú kèqi" },
      { q: "Yes / No", a: "Shì / Bù" },
      { q: "Excuse me / Sorry", a: "Qǐngwèn / Duìbuqǐ" },
      { q: "What is your name?", a: "Nǐ jiào shénme míngzi?" },
      { q: "My name is…", a: "Wǒ jiào …" },
      { q: "How are you?", a: "Nǐ hǎo ma?" },
      { q: "I’m fine", a: "Wǒ hěn hǎo" },
      { q: "I don’t understand", a: "Wǒ bù dǒng" },
      { q: "Do you speak English?", a: "Nǐ huì shuō Yīngyǔ ma?" },
      { q: "Where is the bathroom?", a: "Xǐshǒujiān zài nǎr?" },
      { q: "How much is it?", a: "Duōshao qián?" },
      { q: "I would like…", a: "Wǒ xiǎng yào …" },
      { q: "Help!", a: "Jiù mìng a!" },
      { q: "Numbers 1–5", a: "Yī, èr, sān, sì, wǔ" },
      { q: "Days: Mon–Sun", a: "Xīngqī yī, èr, sān, sì, wǔ, liù, rì" },
      { q: "Colors: red/blue/green", a: "Hóng / lán / lǜ" },
      { q: "Cheers!", a: "Gānbēi!" },
    ],
  },
  {
    id: "korean_hangul",
    title: "Korean (Hangul)",
    questions: [
      { q: "Hello / Goodbye", a: "안녕하세요 / 안녕히 가세요" },
      { q: "Please / Thank you", a: "제발 / 감사합니다" },
      { q: "You’re welcome", a: "천만에요" },
      { q: "Yes / No", a: "네 / 아니요" },
      { q: "Excuse me / Sorry", a: "실례합니다 / 미안합니다" },
      { q: "What is your name?", a: "이름이 뭐예요?" },
      { q: "My name is…", a: "제 이름은 …예요/이에요" },
      { q: "How are you?", a: "잘 지내세요?" },
      { q: "I’m fine", a: "잘 지내요" },
      { q: "I don’t understand", a: "이해하지 못해요" },
      { q: "Do you speak English?", a: "영어 하세요?" },
      { q: "Where is the bathroom?", a: "화장실 어디예요?" },
      { q: "How much is it?", a: "얼마예요?" },
      { q: "I would like…", a: "… 주세요" },
      { q: "Help!", a: "도와주세요!" },
      { q: "Numbers 1–5", a: "하나, 둘, 셋, 넷, 다섯" },
      { q: "Days: Mon–Sun", a: "월, 화, 수, 목, 금, 토, 일" },
      { q: "Colors: red/blue/green", a: "빨강 / 파랑 / 초록" },
      { q: "Good morning / night", a: "좋은 아침 / 안녕히 주무세요" },
      { q: "Delicious", a: "맛있어요" },
    ],
  },
  {
    id: "portuguese_basics",
    title: "Portuguese Basics",
    questions: [
      { q: "Hello / Goodbye", a: "Olá / Tchau" },
      { q: "Please / Thank you", a: "Por favor / Obrigado(a)" },
      { q: "You’re welcome", a: "De nada" },
      { q: "Yes / No", a: "Sim / Não" },
      { q: "Excuse me / Sorry", a: "Com licença / Desculpe" },
      { q: "What is your name?", a: "Como você se chama?" },
      { q: "My name is…", a: "Meu nome é…" },
      { q: "How are you?", a: "Como vai?" },
      { q: "I’m fine", a: "Estou bem" },
      { q: "I don’t understand", a: "Não entendo" },
      { q: "Do you speak English?", a: "Você fala inglês?" },
      { q: "Where is the bathroom?", a: "Onde é o banheiro?" },
      { q: "How much is it?", a: "Quanto custa?" },
      { q: "I would like…", a: "Eu gostaria de…" },
      { q: "Help!", a: "Socorro!" },
      { q: "Numbers 1–5", a: "Um, dois, três, quatro, cinco" },
      {
        q: "Days: Mon–Sun",
        a: "Segunda, terça, quarta, quinta, sexta, sábado, domingo",
      },
      { q: "Colors: red/blue/green", a: "Vermelho / azul / verde" },
      { q: "Good morning / night", a: "Bom dia / Boa noite" },
      { q: "Cheers!", a: "Saúde!" },
    ],
  },
  {
    id: "russian_translit",
    title: "Russian (Translit)",
    questions: [
      { q: "Hello / Goodbye", a: "Zdravstvuyte / Do svidaniya" },
      { q: "Please / Thank you", a: "Pozhaluysta / Spasibo" },
      { q: "You’re welcome", a: "Pozhaluysta (you’re welcome too)" },
      { q: "Yes / No", a: "Da / Net" },
      { q: "Excuse me / Sorry", a: "Izvinite / Prostite" },
      { q: "What is your name?", a: "Kak vas zovut?" },
      { q: "My name is…", a: "Menya zovut …" },
      { q: "How are you?", a: "Kak dela?" },
      { q: "I’m fine", a: "Khorosho" },
      { q: "I don’t understand", a: "Ya ne ponimayu" },
      { q: "Do you speak English?", a: "Vy govorite po-angliyski?" },
      { q: "Where is the bathroom?", a: "Gde tualet?" },
      { q: "How much is it?", a: "Skol’ko eto stoit?" },
      { q: "I would like…", a: "Ya by khotel(a) …" },
      { q: "Help!", a: "Pomogite!" },
      { q: "Numbers 1–5", a: "Odin, dva, tri, chetyre, pyat’" },
      { q: "Days: Mon–Sun", a: "Ponedel’nik… Voskresen’e" },
      { q: "Colors: red/blue/green", a: "Krasnyy / siniy / zelyonyy" },
      { q: "Good morning / night", a: "Dobroye utro / Spokoynoy nochi" },
      { q: "Cheers!", a: "Za zdorovye!" },
    ],
  },
  {
    id: "arabic_translit",
    title: "Arabic (Translit)",
    questions: [
      { q: "Hello / Goodbye", a: "Marhaba / Maʿa as-salāma" },
      { q: "Please / Thank you", a: "Min faḍlik / Shukran" },
      { q: "You’re welcome", a: "ʿAfwan" },
      { q: "Yes / No", a: "Naʿam / Lā" },
      { q: "Excuse me / Sorry", a: "ʿAn izinak / Āsif" },
      { q: "What is your name?", a: "Mā ismuka/ismuki?" },
      { q: "My name is…", a: "Ismī …" },
      { q: "How are you?", a: "Kayfa ḥāluka/ḥāluki?" },
      { q: "I’m fine", a: "Ana bikhayr" },
      { q: "I don’t understand", a: "Lā afham" },
      { q: "Do you speak English?", a: "Hal tatakallam al-inglīziyya?" },
      { q: "Where is the bathroom?", a: "Ayna al-ḥammām?" },
      { q: "How much is it?", a: "Bikam hādhā?" },
      { q: "I would like…", a: "Urīdu …" },
      { q: "Help!", a: "Al-ghawth!" },
      { q: "Numbers 1–5", a: "Wāḥid, ithnān, thalātha, arbaʿa, khamsa" },
      { q: "Days: Mon–Sun", a: "Al-ithnayn… Al-aḥad" },
      { q: "Colors: red/blue/green", a: "Aḥmar / azraq / akhḍar" },
      { q: "Good morning / night", a: "Ṣabāḥ al-khayr / Tuṣbiḥ ʿalā khayr" },
      { q: "Peace be upon you", a: "As-salāmu ʿalaykum" },
    ],
  },
  {
    id: "hindi_translit",
    title: "Hindi (Translit)",
    questions: [
      { q: "Hello / Goodbye", a: "Namaste / Alvida" },
      { q: "Please / Thank you", a: "Kripaya / Dhanyavaad" },
      { q: "You’re welcome", a: "Aapka swāgat hai" },
      { q: "Yes / No", a: "Haan / Nahi" },
      { q: "Excuse me / Sorry", a: "Maaf kijiye" },
      { q: "What is your name?", a: "Aapka naam kya hai?" },
      { q: "My name is…", a: "Mera naam … hai" },
      { q: "How are you?", a: "Aap kaise hain?" },
      { q: "I’m fine", a: "Main theek hoon" },
      { q: "I don’t understand", a: "Mujhe samajh nahi aata" },
      { q: "Do you speak English?", a: "Kya aap angrezi bolte hain?" },
      { q: "Where is the bathroom?", a: "Bathroom kahan hai?" },
      { q: "How much is it?", a: "Yeh kitne ka hai?" },
      { q: "I would like…", a: "Mujhe … chahiye" },
      { q: "Help!", a: "Madad!" },
      { q: "Numbers 1–5", a: "Ek, do, teen, chaar, paanch" },
      { q: "Days: Mon–Sun", a: "Som, Mangal, Budh, Guru, Shukr, Shani, Ravi" },
      { q: "Colors: red/blue/green", a: "Laal / neela / hara" },
      { q: "Good morning / night", a: "Suprabhat / Shubh raatri" },
      { q: "Where are you from?", a: "Aap kahan se hain?" },
    ],
  },
];
