const fs=require('fs'),p='app/data/flashcards.json';
if(!fs.existsSync(p)) fs.writeFileSync(p,JSON.stringify({topics:[]},null,2));
const d=JSON.parse(fs.readFileSync(p,'utf8'));
function U(title,pairs){const i=(d.topics||[]).findIndex(t=>t.title===title);const cards=pairs.map(([q,a])=>({q,a}));if(i>=0)d.topics[i]={title,cards};else(d.topics||(d.topics=[])).push({title,cards});}

U("US History I",[
["Year of Declaration of Independence","1776"],
["Author of Declaration","Thomas Jefferson"],
["First US President","George Washington"],
["Civil War years","1861–1865"],
["Emancipation Proclamation year","1863"],
["Louisiana Purchase year","1803"],
["Great Depression began","1929"],
["New Deal president","Franklin D. Roosevelt"],
["Bill of Rights count","10 amendments"],
["Women’s suffrage amendment","19th Amendment"],
["Abolished slavery amendment","13th Amendment"],
["Cold War opponents","USA and USSR"],
["Watergate president","Richard Nixon"],
["Civil Rights Act year","1964"],
["Brown v. Board decision","Desegregated schools"],
["Monroe Doctrine aim","Oppose European interference"],
["Transcontinental railroad completed","1869"],
["Pearl Harbor date","Dec 7, 1941"],
["Marshall Plan purpose","European recovery aid"],
["Boston Tea Party protest of","Taxation without representation"]
]);

U("World History I",[
["Ancient Egyptian river","Nile"],
["Birthplace of democracy","Athens"],
["Rome fell in West","476 CE"],
["Silk Road connected","China and Mediterranean"],
["Genghis Khan led","Mongol Empire"],
["Renaissance city","Florence"],
["95 Theses author","Martin Luther"],
["Age of Exploration motive","Trade routes and wealth"],
["French Revolution year","1789"],
["Industrial Revolution start","Britain"],
["Ottoman capital","Constantinople/Istanbul"],
["Meiji Restoration country","Japan"],
["Cold War ended","1991"],
["Magna Carta year","1215"],
["Printing press inventor","Johannes Gutenberg"],
["Black Death century","14th"],
["Mughal architecture icon","Taj Mahal"],
["Byzantine holy church","Hagia Sophia"],
["Zulu leader","Shaka"],
["Great Wall purpose","Defense against invasions"]
]);

U("Economics Basics",[
["Opportunity cost","Next best alternative forgone"],
["Supply law","Price up → quantity supplied up"],
["Demand law","Price up → quantity demanded down"],
["Elastic demand","Sensitive to price changes"],
["GDP meaning","Value of goods/services produced"],
["Inflation","General rise in prices"],
["CPI measures","Consumer price changes"],
["Fiscal policy","Government spending/taxes"],
["Monetary policy","Central bank money/interest"],
["Unemployment types","Frictional, structural, cyclical"],
["Comparative advantage","Lower opportunity cost"],
["Market equilibrium","Supply equals demand"],
["Price ceiling effect","Shortage risk"],
["Price floor effect","Surplus risk"],
["Marginal cost","Cost of one more unit"],
["Diminishing returns","Extra input yields less output"],
["Public goods trait","Non-rival, non-excludable"],
["Externality example","Pollution"],
["Utility","Satisfaction from consumption"],
["Gini coefficient","Income inequality measure"]
]);

U("Finance Basics",[
["NPV","Present value of cash flows minus cost"],
["IRR","Discount rate with NPV=0"],
["Payback period","Time to recover investment"],
["Diversification goal","Reduce risk"],
["ETF","Exchange-traded fund"],
["Beta measures","Market risk sensitivity"],
["P/E ratio","Price per share / earnings per share"],
["Dividend yield","Dividend/price"],
["Bond coupon","Periodic interest payment"],
["Yield to maturity","Total return if held to maturity"],
["Credit risk","Default risk"],
["Liquidity","Ease of converting to cash"],
["Compound interest","Interest on interest"],
["Time value of money","Money now > money later"],
["DCF","Discounted cash flow method"],
["Market capitalization","Price × shares"],
["Alpha","Excess return over benchmark"],
["Sharpe ratio","Return minus risk-free over volatility"],
["Hedge","Offset risk position"],
["Stop-loss order","Auto-sell at set price"]
]);

U("Astronomy",[
["Nearest star to Earth","Sun"],
["Galaxy we live in","Milky Way"],
["Red planet","Mars"],
["Hottest planet","Venus"],
["Largest planet","Jupiter"],
["Dwarf planet in Kuiper Belt","Pluto"],
["Light-year","Distance light travels in a year"],
["Supernova","Exploding star"],
["Black hole feature","Escape velocity exceeds light"],
["Exoplanet","Planet outside solar system"],
["Spectroscopy use","Analyze composition via light"],
["H-R diagram plots","Luminosity vs temperature"],
["Nebula","Cloud of gas and dust"],
["Tides caused by","Moon and Sun gravity"],
["Earth’s axial tilt","~23.5°"],
["Aurora cause","Solar wind + magnetosphere"],
["Eclipse types","Solar and lunar"],
["Cosmic microwave background","Relic radiation from Big Bang"],
["Dark matter evidence","Galaxy rotation curves"],
["Hubble’s law","Recession speed ∝ distance"]
]);

U("Earth Science",[
["Rock cycle types","Igneous, sedimentary, metamorphic"],
["Plate tectonics move at","cm per year"],
["Richter scale measures","Earthquake magnitude"],
["Epicenter","Point on surface above focus"],
["Weathering vs erosion","Breakdown vs transport"],
["Greenhouse gases","CO2, CH4, N2O"],
["Ozone layer location","Stratosphere"],
["Water table","Top of saturated zone"],
["El Niño","Warming of Pacific waters"],
["Hurricane energy source","Warm ocean water"],
["Mineral hardness scale","Mohs scale"],
["Soil horizons","O, A, B, C"],
["Fossil fuels","Coal, oil, natural gas"],
["Karst forms from","Dissolution of limestone"],
["Desertification","Land becomes desert-like"],
["Tsunami cause","Seafloor displacement"],
["Volcano types","Shield, composite, cinder cone"],
["Glaciers shape","U-shaped valleys"],
["River meander","Curving channel bends"],
["Isostasy","Crust floats on mantle"]
]);

U("Anatomy II",[
["Brain lobes","Frontal, parietal, temporal, occipital"],
["Cerebellum role","Coordination and balance"],
["Hypothalamus role","Homeostasis, hormones"],
["Cranial nerves count","12 pairs"],
["Alimentary canal start","Mouth"],
["Bile made by","Liver"],
["Insulin made by","Pancreas"],
["Alveoli function","Gas exchange"],
[" SA node location","Right atrium"],
["Cornea function","Refracts light"],
["Rod cells","Low-light vision"],
["Nephron loop name","Loop of Henle"],
["Glomerulus","Capillary tuft filtering blood"],
["Axon","Carries nerve impulse away"],
["Myelin","Insulation of axons"],
["Synovial fluid","Lubricates joints"],
["Lymph nodes","Filter lymph"],
["Spleen role","Immune and blood filter"],
["Thyroid hormone","Thyroxine (T4)"],
["Adrenal medulla hormone","Adrenaline"]
]);

U("Physiology",[
["Homeostasis","Maintain internal constancy"],
["Cardiac output","Heart rate × stroke volume"],
["Tidal volume","Air per normal breath"],
["Hemoglobin binds","Oxygen"],
["Bohr effect","CO2/H+ reduce O2 affinity"],
["Action potential ion","Na+ influx then K+ efflux"],
["Synapse transmitter","Chemical or electrical"],
["Insulin effect","Lower blood glucose"],
["Glucagon effect","Raise blood glucose"],
["Basal metabolic rate","Energy at rest"],
["Kidney filtration site","Glomerulus"],
["ADH effect","Increase water reabsorption"],
["Muscle energy immediate","ATP and creatine phosphate"],
["Lactate forms when","Anaerobic glycolysis"],
["Baroreceptors sense","Blood pressure"],
["Pulmonary circulation","Heart→lungs→heart"],
["SA node role","Pacemaker"],
["Peristalsis","Wave-like gut motion"],
["Reflex arc","Sensory→interneuron→motor"],
["Fever mediator","Pyrogens reset set point"]
]);

U("Genetics",[
["Chromosome count human","46"],
["Allele","Variant of a gene"],
["Genotype","Genetic makeup"],
["Phenotype","Observable traits"],
["Dominant allele","Expressed with one copy"],
["Recessive allele","Needs two copies"],
["Codominance example","AB blood type"],
["Incomplete dominance","Blended phenotype"],
["Punnett square","Predicts crosses"],
["Mendel’s law of segregation","Alleles separate into gametes"],
["Independent assortment","Genes sort independently"],
["Crossing over","Exchange in meiosis I"],
["Mutation","Change in DNA sequence"],
["Point mutation","Single base change"],
["Frameshift","Insertion/deletion not multiple of 3"],
["Homozygous","Same alleles"],
["Heterozygous","Different alleles"],
["X-linked inheritance","Gene on X chromosome"],
["Mitochondrial DNA","Maternal inheritance"],
["Genome","All genetic material"]
]);

U("Programming: TypeScript",[
["Type annotation syntax","const x: number"],
["Interface keyword","interface"],
["Union type","string | number"],
["Generics","function f<T>(x:T)"],
["Enum","enum Color {Red}"],
["Type alias","type ID = string"],
["Readonly","readonly prop"],
["Partial utility","Partial<T>"],
["Pick utility","Pick<T,K>"],
["Record utility","Record<K,T>"],
["NonNullable","Exclude null and undefined"],
["Unknown vs any","Unknown needs narrowing"],
["Narrowing example","if (typeof x==='string')"],
["Never type","No values"],
["Optional property","prop?: T"],
["Assertion","value as Type"],
["Module import","import x from 'm'"],
["Strict mode flag","strict: true"],
["tsconfig purpose","Compiler options"],
["Declare global","declare global { }"]
]);

U("Programming: React",[
["Component type","Function components"],
["JSX","Syntax to describe UI"],
["State hook","useState"],
["Effect hook","useEffect"],
["Memoization","React.memo/useMemo"],
["Context API","useContext"],
["Ref hook","useRef"],
["Key purpose","Identify list items"],
["Controlled input","Value from state"],
["Prop drilling","Passing props through many levels"],
["Suspense","Await async UI"],
["Error boundary","Catches render errors"],
["SSR","Server-side rendering"],
["Hydration","Attach events to SSR HTML"],
["Reconciliation","Diffing virtual DOM"],
["Portal","Render into different DOM node"],
["Fragment","<>...</>"],
["StrictMode","Extra checks in dev"],
["Concurrent features","Responsive rendering"],
["useReducer","State reducer pattern"]
]);

U("Programming: SQL Advanced",[
["Window function","OVER clause operations"],
["ROW_NUMBER","Sequential rank per partition"],
["CTE","WITH clause"],
["Recursive CTE","WITH RECURSIVE"],
["Index-only scan","Uses index without table"],
["Covering index","Contains all needed columns"],
["Query hint","Optimizer directive"],
["EXPLAIN ANALYZE","Execute and show plan"],
["Materialized view","Stored result of query"],
["Partitioning","Split table by key/range"],
["Foreign key cascade","Auto update/delete related rows"],
["Isolation serializable","Full ACID isolation"],
["Deadlock detection","Abort one transaction"],
["Lock escalation","Row to table lock"],
["Bitmap index","Efficient boolean combos"],
["Full-text search","Token-based search"],
["UPSERT","INSERT ... ON CONFLICT"],
["MERGE","Conditional insert/update"],
["Lateral join","Join with subquery uses left row"],
["UNNEST","Expand array to rows"]
]);

U("Networking Security",[
["Firewall","Filters traffic by rules"],
["IDS/IPS","Detect/prevent intrusions"],
["VPN","Encrypted tunnel"],
["TLS","Transport security"],
["Certificate authority","Issues digital certs"],
["HSTS","Force HTTPS"],
["CORS policy","Cross-origin rules"],
["CSRF token","Prevents forged requests"],
["XSS","Inject scripts into pages"],
["SQL injection","Manipulate DB via input"],
["SSRF","Server makes internal requests"],
["WAF","Web application firewall"],
["Rate limiting","Throttle requests"],
["Brute force","Many guesses attack"],
["Salting passwords","Add randomness before hashing"],
["PBKDF2/BCrypt/Argon2","Key-stretching hashes"],
["Zero trust","Verify every request"],
["Principle of least privilege","Minimal access"],
["Secrets rotation","Regularly replace keys"],
["Audit logging","Track security events"]
]);

U("Linux CLI",[
["List files","ls"],
["Change directory","cd"],
["Print working dir","pwd"],
["Copy file","cp"],
["Move/rename","mv"],
["Remove file","rm"],
["Search text","grep"],
["Find files","find"],
["Show processes","ps"],
["Kill by PID","kill"],
["Permissions view","ls -l"],
["Change mode","chmod"],
["Change owner","chown"],
["Archive tar","tar -czf"],
["Stream pager","less"],
["Link hard/soft","ln, ln -s"],
["Env vars","export NAME=VAL"],
["Shell config","~/.bashrc"],
["Package install Debian","apt install"],
["Elevate command","sudo"]
]);

U("Git & GitHub",[
["Init repo","git init"],
["Stage files","git add"],
["Commit","git commit -m"],
["Branch create","git checkout -b"],
["Merge","git merge"],
["Rebase","git rebase"],
["Stash","git stash"],
["Log","git log"],
["Diff","git diff"],
["Remote add","git remote add"],
["Push","git push"],
["Pull","git pull"],
["Clone","git clone"],
["Tag","git tag"],
["Squash merge","Combine commits"],
["Pull request","Propose changes"],
["Issue","Track tasks/bugs"],
["Actions","CI/CD on GitHub"],
["Release","Versioned build"],
["Semantic versioning","MAJOR.MINOR.PATCH"]
]);

U("Regex",[
["Dot .","Any char except newline"],
["Star *","Zero or more"],
["Plus +","One or more"],
["Question ?","Optional"],
["Character class","[abc]"],
["Negated class","[^abc]"],
["Anchors","^ start, $ end"],
["Grouping","( )"],
["Alternation","a|b"],
["Backreference","\\1"],
["Word boundary","\\b"],
["Digit class","\\d"],
["Whitespace","\\s"],
["Greedy vs lazy",".* vs .*?"],
["Lookahead","(?=...)"],
["Negative lookahead","(?!...)"],
["Lookbehind","(?<=...)"],
["Escape","\\."],
["Flags","i g m s u y"],
["Replace capture","$1 in replacement"]
]);

U("Design UX",[
["Heuristic: visibility","Show system status"],
["Match real world","Use familiar concepts"],
["User control","Support undo/redo"],
["Consistency","Same patterns across app"],
["Error prevention","Constrain invalid actions"],
["Recognition over recall","Visible choices"],
["Flexibility","Shortcuts for experts"],
["Aesthetic minimalism","Remove clutter"],
["Help users recover","Clear errors"],
["Help documentation","Findable guidance"],
["Fitts’s Law","Target size vs distance"],
["Hick’s Law","More choices = slower"],
["Gestalt proximity","Group nearby elements"],
["Contrast","Improve readability"],
["Typography","Hierarchy and scale"],
["Affordance","Appearance suggests use"],
["Feedback","Immediate response"],
["Progressive disclosure","Reveal complexity gradually"],
["Accessibility contrast","At least 4.5:1"],
["Mobile touch target","~44px recommended"]
]);

U("Project Management",[
["Scope","Work to deliver product"],
["Stakeholder","Affected by project"],
["WBS","Work breakdown structure"],
["Critical path","Longest path of tasks"],
["Gantt chart","Timeline bar chart"],
["Risk register","List of risks and plans"],
["Dependency","Task needs another"],
["Agile sprint","Time-boxed iteration"],
["User story","Feature from user view"],
["Acceptance criteria","Conditions of satisfaction"],
["Burndown chart","Work remaining over time"],
["Velocity","Work per sprint"],
["Retrospective","Inspect and adapt"],
["Kanban WIP limit","Cap concurrent work"],
["RACI","Roles: responsible etc"],
["Change control","Approve changes"],
["Baseline","Approved plan"],
["Earned value","Cost/schedule performance"],
["CPR metric","Cost performance ratio"],
["Buffer","Contingency time or cost"]
]);

U("Psychology Basics",[
["Classical conditioning","Learning via association"],
["Operant conditioning","Learning via consequences"],
["Positive reinforcement","Add reward to increase behavior"],
["Negative reinforcement","Remove aversive to increase behavior"],
["Punishment","Decrease behavior"],
["Working memory","Short-term processing"],
["Long-term memory","Enduring storage"],
["Big Five traits","OCEAN"],
["Cognitive dissonance","Inconsistency discomfort"],
["Heuristic","Mental shortcut"],
["Bias confirmation","Favoring confirming info"],
["Placebo effect","Benefit from expectation"],
["Attachment styles","Secure, anxious, avoidant"],
["Piaget stages","Sensorimotor→formal operations"],
["Maslow pyramid top","Self-actualization"],
["Classical vs operant","Association vs consequences"],
["Schemas","Mental frameworks"],
["Motivation intrinsic","Internal satisfaction"],
["Emotion James-Lange","Physiology before emotion"],
["Social facilitation","Better with audience"]
]);

U("Art History",[
["Mona Lisa painter","Leonardo da Vinci"],
["Sistine Chapel ceiling","Michelangelo"],
["Starry Night artist","Vincent van Gogh"],
["Guernica artist","Pablo Picasso"],
["The Persistence of Memory","Salvador Dalí"],
["Impressionism origin","19th-century France"],
["The Scream artist","Edvard Munch"],
["Girl with a Pearl Earring","Johannes Vermeer"],
["American Gothic","Grant Wood"],
["The Birth of Venus","Sandro Botticelli"],
["The Night Watch","Rembrandt"],
["Pointillism pioneer","Georges Seurat"],
["Cubism founders","Picasso and Braque"],
["Surrealism focus","Dreamlike imagery"],
["Baroque trait","Dramatic light and movement"],
["Renaissance trait","Humanism and realism"],
["Dada","Anti-art movement"],
["Fauvism","Bold color, simplified form"],
["Pop Art icon","Andy Warhol"],
["Abstract Expressionism","Jackson Pollock"]
]);

fs.writeFileSync(p,JSON.stringify(d,null,2));
console.log('topics_total',d.topics.length,'cards_total',d.topics.reduce((s,t)=>s+t.cards.length,0));
