const fs=require('fs'),p='app/data/flashcards.json';
if(!fs.existsSync(p)) fs.writeFileSync(p,JSON.stringify({topics:[]},null,2));
const d=JSON.parse(fs.readFileSync(p,'utf8'));
function U(title,pairs){const i=(d.topics||[]).findIndex(t=>t.title===title);const cards=pairs.map(([q,a])=>({q,a}));if(i>=0)d.topics[i]={title,cards};else(d.topics||(d.topics=[])).push({title,cards});}

U("Algebra II",[
["Solve 5x−3=2x+12","x=5"],
["Vertex of y=2(x−3)^2+4","(3,4)"],
["Roots of x^2−9x+20=0","x=4,5"],
["Sum of roots ax^2+bx+c","−b/a"],
["Product of roots ax^2+bx+c","c/a"],
["Complete square: x^2+6x","(x+3)^2−9"],
["Factor x^2−2x−8","(x−4)(x+2)"],
["Domain of 1/(x−2)","x≠2"],
["Solve |2x−1|=5","x=3 or x=−2"],
["Solve 3^x=27","x=3"],
["Log rule log(a^b)","b·log a"],
["Solve 2^x=5","x=log_2 5"],
["Inequality 2x+1>7","x>3"],
["Asymptote y= (2x+1)/(x−3)","x=3"],
["Geometric mean of 4,9","6"],
["Arithmetic mean of 2,10","6"],
["Sequence a_n=3n+1","Linear, d=3"],
["Sequence a_n=2·5^{n}","Geometric, r=5"],
["Solve system x+y=7,x−y=1","x=4,y=3"],
["Binomial coeff C(6,2)","15"]
]);

U("Geometry Advanced",[
["Exterior angle of triangle","= sum of two remote interiors"],
["Area of trapezoid","(b1+b2)h/2"],
["Area of regular hexagon (side s)","(3√3/2)s^2"],
["Diagonal of cube (edge a)","a√3"],
["Area of equilateral (side s)","(√3/4)s^2"],
["Apothem meaning","Inradius of regular polygon"],
["Chord longest where","Through center (diameter)"],
["Arc length (θ radians)","θr"],
["Sector area (θ radians)","(1/2)r^2θ"],
["Inscribed angle","Half intercepted arc"],
["Tangent–radius angle","90°"],
["Similar triangles ratio","Sides proportional"],
["Heron’s s","(a+b+c)/2"],
["Circumference to diameter","π"],
["Volume of cone","(1/3)πr^2h"],
["Surface area sphere","4πr^2"],
["45–45–90 triangle sides","x,x,x√2"],
["30–60–90 sides","x,x√3,2x"],
["Parallel lines alt. interior","Congruent"],
["Median of triangle count","3"]
]);

U("Calculus I",[
["Derivative of x^n","nx^{n−1}"],
["d/dx(sin x)","cos x"],
["d/dx(cos x)","−sin x"],
["d/dx(e^x)","e^x"],
["d/dx(ln x)","1/x"],
["Product rule","(fg)'=f'g+fg'"],
["Quotient rule","(f/g)'=(f'g−fg')/g^2"],
["Chain rule","(f∘g)'=f'(g)g'"],
["∫ x^n dx","x^{n+1}/(n+1)+C (n≠−1)"],
["∫ 1/x dx","ln|x|+C"],
["∫ cos x dx","sin x+C"],
["∫ sin x dx","−cos x+C"],
["Critical point","f'(x)=0 or undefined"],
["Local max test","f' changes +→−"],
["Local min test","f' changes −→+"],
["Concave up","f''>0"],
["Inflection point","f'' changes sign"],
["Mean Value Theorem","f'(c)=(f(b)−f(a))/(b−a)"],
["L'Hôpital uses","0/0 or ∞/∞"],
["Area under curve","Definite integral"]
]);

U("Calculus II",[
["∫ e^{ax} dx","(1/a)e^{ax}+C"],
["∫ 1/(x^2+1) dx","arctan x + C"],
["∫ 1/√(1−x^2) dx","arcsin x + C"],
["Integration by parts","∫udv=uv−∫vdu"],
["u-substitution","Let u=g(x) to simplify"],
["Geometric series sum","a/(1−r), |r|<1"],
["Converges: p-series ∑1/n^p","p>1"],
["Diverges: harmonic ∑1/n","Yes"],
["Ratio test","L=lim|a_{n+1}/a_n|"],
["If L<1 (ratio test)","Converges"],
["If L>1 (ratio test)","Diverges"],
["Alternating test needs","Decreasing terms →0"],
["Taylor series e^x","∑ x^n/n!"],
["Taylor series sin x","∑ (−1)^n x^{2n+1}/(2n+1)!"],
["Arc length","∫√(1+(y')^2) dx"],
["Surface of revolution","2π∫ y√(1+(y')^2) dx"],
["Improper integral","Infinite bound or unbounded integrand"],
["Partial fractions","Decompose rational function"],
["Center of mass 1D","(∫xρ dx)/(∫ρ dx)"],
["Work by variable force","∫F(x) dx"]
]);

U("Statistics II",[
["Bernoulli mean","p"],
["Bernoulli variance","p(1−p)"],
["Binomial mean","np"],
["Binomial variance","np(1−p)"],
["Poisson mean","λ"],
["Poisson variance","λ"],
["Normal 68–95–99.7","σ,2σ,3σ"],
["Z to probability","Φ(z)"],
["t-distribution use","Unknown σ, small n"],
["CLT core idea","Sample mean ≈ Normal"],
["CI for mean (known σ)","x̄±z*σ/√n"],
["CI for mean (unknown σ)","x̄±t*s/√n"],
["Type I error","False positive"],
["Type II error","False negative"],
["Power","1−β"],
["p-value meaning","P(data|H0 true)"],
["Chi-square test","Categorical independence"],
["Correlation r range","−1 to 1"],
["Regression slope meaning","Δy per unit x"],
["Homoscedasticity","Constant variance of errors"]
]);

U("Physics: Mechanics",[
["Displacement","Δx"],
["Velocity","dx/dt"],
["Acceleration","dv/dt"],
["Newton’s 2nd","F=ma"],
["Weight","mg"],
["Friction kinetic","μ_k N"],
["Work","F·d cosθ"],
["Power","dW/dt"],
["Momentum","mv"],
["Impulse","FΔt=Δp"],
["Elastic collision","KE conserved"],
["Inelastic collision","KE not conserved"],
["Centripetal accel","v^2/r"],
["Period of circle","T=2πr/v"],
["Hooke’s law","F=−kx"],
["SHO period","T=2π√(m/k)"],
["Grav potential near Earth","mgh"],
["Projectile vy at top","0"],
["Torque","r×F"],
["Rotational KE","(1/2)Iω^2"]
]);

U("Physics: E&M",[
["Coulomb’s law","F=k q1 q2 / r^2"],
["Electric field","F/q"],
["Potential difference","Work per charge"],
["Capacitance","C=Q/V"],
["RC time constant","τ=RC"],
["Magnetic force","q v B sinθ"],
["Right-hand rule","v×B direction"],
["Faraday’s law","EMF=−dΦ/dt"],
["Ohm’s law","V=IR"],
["Resistors series","Add"],
["Resistors parallel","Reciprocal add"],
["Power electric","P=VI"],
["Kirchhoff current","ΣI_in=ΣI_out"],
["Kirchhoff loop","ΣΔV=0"],
["Drift velocity","Avg carrier speed"],
["Dielectric effect","Increases capacitance"],
["Solenoid field","μ0 n I"],
["RL time constant","L/R"],
["AC RMS voltage","V/√2"],
["Transformer ideal","V2/V1 = N2/N1"]
]);

U("Organic Chemistry",[
["Alkane formula","C_nH_{2n+2}"],
["Alkene formula","C_nH_{2n}"],
["Alkyne formula","C_nH_{2n−2}"],
["Aromatic ring","Benzene core"],
["Isomers","Same formula, diff arrangement"],
["Enantiomers","Non-superimposable mirror images"],
["SN1 rate","k[substrate]"],
["SN2 rate","k[substrate][nucleophile]"],
["Markovnikov rule","H adds to most H-rich carbon"],
["Zaitsev rule","Most substituted alkene favored"],
["E1 vs E2","Unimolecular vs bimolecular elimination"],
["Hydrogenation","Add H2 across double bond"],
["Oxidation of alcohol 1°","To aldehyde→acid"],
["Reduction of carbonyl","To alcohol"],
["Protecting group use","Temporary masking of reactivity"],
["Tautomerization","Keto–enol interconversion"],
["Stereocenter","Carbon with four different groups"],
["R/S configuration","Cahn–Ingold–Prelog rules"],
["IR C=O stretch","~1700 cm⁻¹"],
["NMR TMS","Reference at 0 ppm"]
]);

U("Human Anatomy",[
["Heart chambers","2 atria, 2 ventricles"],
["Gas exchange site","Alveoli"],
["Kidney unit","Nephron"],
["Neurotransmitter gap","Synapse"],
["Largest organ","Skin"],
["Liver function","Detox, metabolism, bile"],
["Pancreas role","Insulin, enzymes"],
["Small intestine parts","Duodenum, jejunum, ileum"],
["Bone cell builder","Osteoblast"],
["Bone cell breaker","Osteoclast"],
["Muscle types","Skeletal, smooth, cardiac"],
["SA node","Pacemaker"],
["Hemoglobin job","Carry O2"],
["WBC role","Immunity"],
["Platelet role","Clotting"],
["Anterior vs posterior","Front vs back"],
["Medial vs lateral","Toward midline vs away"],
["Proximal vs distal","Near trunk vs far"],
["CNS vs PNS","Brain/spinal vs nerves"],
["Endocrine glands","Thyroid, adrenal, pituitary"]
]);

U("Microbiology",[
["Prokaryote","No nucleus"],
["Gram-positive wall","Thick peptidoglycan"],
["Gram-negative wall","Thin peptidoglycan + outer membrane"],
["Flagella use","Motility"],
["Endospore","Dormant, resistant cell"],
["Binary fission","Asexual division"],
["Plasmid","Small circular DNA"],
["Conjugation","DNA transfer via pilus"],
["Transformation","Uptake of naked DNA"],
["Transduction","Phage-mediated DNA transfer"],
["Antibiotic target","Cell wall, ribosome, DNA gyrase"],
["Biofilm","Surface-attached community"],
["Quorum sensing","Density-dependent signaling"],
["Sterilization","Eliminate all microbes"],
["Disinfection","Reduce pathogens"],
["Aseptic technique","Prevent contamination"],
["Normal flora","Commensal microbes"],
["Pathogenicity","Ability to cause disease"],
["Virulence factor","Enhances pathogenicity"],
["Bacteriophage","Virus infecting bacteria"]
]);

U("Computer Networks",[
["IPv4 length","32 bits"],
["IPv6 length","128 bits"],
["ARP","IP↔MAC resolution"],
["DHCP","Dynamic IP assignment"],
["DNS A record","IPv4 address"],
["DNS AAAA record","IPv6 address"],
["TCP port HTTP","80"],
["HTTPS port","443"],
["SSH port","22"],
["SMTP port","25"],
["IMAP port","143"],
["CIDR /24 hosts","256 addresses (254 usable)"],
["Subnetting purpose","Segment networks"],
["QoS","Traffic prioritization"],
["NTP","Clock sync"],
["Traceroute shows","Hops and latency"],
["TTL","Hop limit"],
["Anycast","Same IP at many edges"],
["MSS","Max TCP segment size"],
["Window size","Flow control"]
]);

U("Databases: SQL",[
["SELECT all columns","SELECT * FROM t;"],
["WHERE clause","Filter rows"],
["ORDER BY x DESC","Sort descending by x"],
["JOIN default","INNER JOIN"],
["LEFT JOIN","All left rows, matching right"],
["GROUP BY","Aggregate groups"],
["HAVING","Filter aggregated groups"],
["COUNT(*)","Row count"],
["AVG(col)","Mean of col"],
["MAX/MIN","Extrema"],
["PRIMARY KEY","Unique identifier"],
["FOREIGN KEY","References other table"],
["UNIQUE","No duplicate values"],
["INDEX","Speed reads by column"],
["TRANSACTION","BEGIN...COMMIT/ROLLBACK"],
["IS NULL","Null check"],
["LIKE 'A%'","Starts with A"],
["IN (..)", "Membership test"],
["UNION vs UNION ALL","Distinct vs allow duplicates"],
["EXPLAIN","Show query plan"]
]);

U("Web Dev: HTML/CSS",[
["<main> role","Primary content"],
["<nav>","Site navigation"],
["Alt text use","Describe images"],
["Flex main axis","Row/column"],
["Grid tracks","Rows and columns"],
["Position: sticky","Sticks within container"],
["z-index works on","Positioned elements"],
["rem unit base","Root font size"],
["Media query","@media (max-width:...)"],
["ARIA label","aria-label"],
["Contrast ratio aim","≥ 4.5:1"],
["Focus ring","Visible keyboard focus"],
["Semantic form","<label for=...>"],
["SVG scalable","Vector graphics"],
["Responsive img","srcset/sizes"],
["Preload","<link rel=preload>"],
["Defer script","<script defer>"],
["CSS variable","--name: value"],
["Transition","property duration easing"],
["Transform","translate/scale/rotate"]
]);

U("JavaScript Advanced",[
["Closure","Function with captured scope"],
["Hoisting","Declarations moved to top"],
["This in arrow fn","Lexically bound"],
["Event loop queues","Macro/microtasks"],
["Promise.resolve( )","Create settled promise"],
["async returns","Promise"],
["await waits","Promise resolution"],
["Deep copy tool","structuredClone"],
["Map vs Object","Any keys vs string/symbol keys"],
["Set vs Array","Unique elements"],
["WeakMap use","Keys GC-friendly"],
["Prototype chain","Inheritance path"],
["Class fields","Public/private properties"],
["Import syntax","import x from 'm'"],
["Dynamic import","import('m')"],
["Debounce","Delay until idle"],
["Throttle","Limit calls per interval"],
["Intl API","Formatting dates/numbers"],
["Web Worker","Background thread"],
["LocalStorage limit","~5–10 MB"]
]);

U("Python Advanced",[
["List vs tuple","Mutable vs immutable"],
["Dict order","Insertion-ordered (3.7+)"],
["GIL","One bytecode thread at a time"],
["Async keywords","async/await"],
["Contextlib","Context managers"],
["Dataclasses","Auto __init__/repr"],
["Type hints","from typing import ..."],
["Generators","yield produce iterables"],
["itertools","Efficient iterator tools"],
["functools.lru_cache","Memoization"],
["pathlib.Path","OO filesystem paths"],
["venv","Isolated environment"],
["pip freeze","List deps"],
["poetry","Package/dependency tool"],
["pydantic","Data validation"],
["pytest","Testing framework"],
["logging levels","DEBUG..CRITICAL"],
["multiprocessing","Bypass GIL with processes"],
["subprocess.run","Spawn processes"],
["sqlite3","Built-in DB"]
]);

U("Data Structures Advanced",[
["Red-Black property","Balanced by color rules"],
["AVL balance factor","−1,0,1"],
["B+ tree","All keys in leaves"],
["Skip list","Layered probabilistic lists"],
["Treap","BST + heap priority"],
["Splay tree","Move accessed to root"],
["K-d tree","k-dimensional splits"],
["Quadtree","2D space partition"],
["Bloom filter","Probabilistic membership"],
["Cuckoo hash","Two tables rehashing"],
["Trie compression","Radix tree"],
["Disjoint-set ops","Find/Union"],
["Union by rank","Attach smaller tree"],
["Path compression","Flatten structure"],
["Segment tree lazy","Deferred updates"],
["Fenwick tree","Binary indexed tree"],
["LRU via","Map + doubly list"],
["LFU cache","Least frequently used"],
["ROPE","Efficient string edits"],
["Suffix array","Sorted suffix indices"]
]);

U("Algorithms Patterns",[
["Two-pointer","Scan from both ends"],
["Sliding window","Maintain range state"],
["Binary search","Halve search space"],
["Divide and conquer","Split and combine"],
["Greedy","Local optimal choice"],
["Dynamic programming","Memoize subproblems"],
["Backtracking","Try/undo choices"],
["Sweep line","Process events in order"],
["Union-find","Merge connectivity"],
["Meet-in-the-middle","Split search to halves"],
["Graph coloring","Assign colors to vertices"],
["Topological order","Linearize DAG"],
["Dijkstra","SP with nonnegative edges"],
["Bellman-Ford","SP with negatives"],
["Kruskal","MST by light edges"],
["Prim","MST by growth"],
["KMP","Linear pattern match"],
["Trie-based search","Prefix queries"],
["Branch and bound","Prune by bounds"],
["Simulated annealing","Probabilistic optimization"]
]);

U("Operating Systems",[
["Monolithic kernel","All services in kernel"],
["Microkernel","Minimal kernel, user services"],
["Preemptive scheduling","Kernel interrupts tasks"],
["Round-robin","Time-slice per task"],
["Priority inversion","Low blocks high"],
["Futex","Fast user-space mutex"],
["NUMA","Non-uniform memory access"],
["Copy-on-write fork","Pages shared until write"],
["Huge pages","Reduce TLB misses"],
["Dirty page","Modified, needs writeback"],
["Dirty bit","Marks modified page"],
["Page fault","Access unmapped page"],
["Thrashing","Excessive paging"],
["I/O scheduler","Order disk requests"],
["Ephemeral port","Temporary client port"],
["cgroups","Resource control"],
["namespaces","Resource isolation"],
["seccomp","Syscall filtering"],
["strace","Syscall tracer"],
["ulimit","Per-process resource limits"]
]);

U("Cloud: AWS Focus",[
["EC2","Virtual servers"],
["S3","Object storage"],
["RDS","Managed relational DB"],
["DynamoDB","NoSQL key-value"],
["Lambda","Serverless compute"],
["API Gateway","Front door for APIs"],
["ECS/EKS","Container orchestration"],
["CloudFront","CDN"],
["VPC","Virtual network"],
["Route 53","DNS"],
["ELB/ALB/NLB","Load balancers"],
["IAM","Access control"],
["KMS","Key management"],
["CloudWatch","Logs/metrics/alarms"],
["CloudTrail","API audit logs"],
["SQS","Message queue"],
["SNS","Pub/Sub"],
["Glue","ETL service"],
["Athena","Query S3 with SQL"],
["Redshift","Data warehouse"]
]);

U("Japanese Travel II",[
["Where is the station?","駅はどこですか (Eki wa doko desu ka)"],
["One ticket to Tokyo","東京まで一枚お願いします (Tōkyō made ichimai onegai shimasu)"],
["Platform number?","何番線ですか (Nan-bansen desu ka)"],
["Does this stop here?","ここに止まりますか (Koko ni tomarimasu ka)"],
["How long?","どのくらいかかりますか (Dono kurai kakarimasu ka)"],
["I’m lost","道に迷いました (Michi ni mayoimashita)"],
["Help please","助けてください (Tasukete kudasai)"],
["I have a reservation","予約があります (Yoyaku ga arimasu)"],
["Two people","二人です (Futari desu)"],
["Check, please","お会計お願いします (Okaikei onegai shimasu)"],
["No plastic bag","袋はいりません (Fukuro wa irimasen)"],
["I’m allergic to","〜にアレルギーがあります (〜ni arerugī ga arimasu)"],
["Spicy?","辛いですか (Karai desu ka)"],
["Water please","お水をください (Omizu o kudasai)"],
["Bathroom","お手洗い (Otearai)"],
["Good value","お買い得 (Okaidoku)"],
["Beautiful","きれい (Kirei)"],
["Delicious","おいしい (Oishii)"],
["Cheap","安い (Yasui)"],
["Expensive","高い (Takai)"]
]);

fs.writeFileSync(p,JSON.stringify(d,null,2));
console.log('topics_total',d.topics.length,'cards_total',d.topics.reduce((s,t)=>s+t.cards.length,0));
