const fs=require('fs');const path=require('path');
const out=path.join('app','data','packs','pack01_japanese.json');

const topics=[
 "Japanese Essentials","Japanese Greetings","Japanese Travel Phrases","Japanese Dining Phrases","Japanese Numbers",
 "Japanese Time & Date","Japanese Days & Months","Japanese Directions","Japanese Shopping","Japanese Emergencies",
 "Japanese Weather","Japanese Family","Japanese School & Work","Japanese Common Verbs","Japanese Adjectives",
 "Japanese Particles","Kanji N5 Set 1","Kanji N5 Set 2","Kanji N5 Set 3","Kanji N5 Set 4"
];

const dict={
 "Japanese Essentials":[["Hello","こんにちは"],["Good morning","おはようございます"],["Good evening","こんばんは"],["Good night","おやすみなさい"],["Thank you","ありがとうございます"],["Thanks","ありがとう"],["Please","お願いします"],["Excuse me","すみません"],["I’m sorry","ごめんなさい"],["Yes","はい"],["No","いいえ"],["OK","大丈夫です"],["I don’t understand","わかりません"],["Do you speak English?","英語を話せますか"],["One moment please","少々お待ちください"],["I see","なるほど"],["Really?","本当ですか"],["What is this?","これは何ですか"],["Where is the toilet?","トイレはどこですか"],["Help","助けて"]],
 "Japanese Greetings":[["Nice to meet you","はじめまして"],["Please treat me well","よろしくお願いします"],["Long time no see","お久しぶりです"],["See you","またね"],["See you tomorrow","また明日"],["Goodbye","さようなら"],["Welcome","いらっしゃいませ"],["Take care","気をつけて"],["How are you?","お元気ですか"],["I’m fine","元気です"],["Good job","お疲れ様です"],["Congrats","おめでとうございます"],["Happy birthday","お誕生日おめでとう"],["Happy New Year","あけましておめでとうございます"],["Good luck","頑張って"],["Thanks for your work","お疲れ様でした"],["Sorry to bother you","お邪魔します"],["I’m home","ただいま"],["Welcome back","お帰りなさい"],["I’m leaving","行ってきます"]],
 "Japanese Travel Phrases":[["Where is the station?","駅はどこですか"],["I need a taxi","タクシーが必要です"],["How much is the ticket?","切符はいくらですか"],["One way please","片道でお願いします"],["Round trip please","往復でお願いします"],["What time does it leave?","何時に出発しますか"],["What time does it arrive?","何時に到着しますか"],["Platform","ホーム"],["Gate","ゲート"],["Exit","出口"],["Entrance","入口"],["Hotel","ホテル"],["Reservation","予約"],["Passport","パスポート"],["Map","地図"],["Left","左"],["Right","右"],["Straight ahead","まっすぐ"],["Near","近い"],["Far","遠い"]],
 "Japanese Dining Phrases":[["A table for two","二人です"],["Menu please","メニューお願いします"],["Water please","お水をお願いします"],["I’m vegetarian","ベジタリアンです"],["No pork please","豚肉は抜いてください"],["It’s delicious","おいしいです"],["Check please","お会計お願いします"],["Another serving","もう一つお願いします"],["I’m full","お腹いっぱいです"],["What do you recommend?","おすすめは何ですか"],["Without wasabi","わさび抜きで"],["Less spicy please","辛さ控えめでお願いします"],["Allergy","アレルギー"],["Gluten-free","グルテンフリー"],["Hot tea please","お茶をお願いします"],["Cold water please","冷たい水をお願いします"],["Rice","ご飯"],["Soup","スープ"],["Separate bill","別々でお願いします"],["Takeout please","お持ち帰りでお願いします"]],
 "Japanese Numbers":[["0","零/れい"],["1","一/いち"],["2","二/に"],["3","三/さん"],["4","四/し・よん"],["5","五/ご"],["6","六/ろく"],["7","七/しち・なな"],["8","八/はち"],["9","九/きゅう・く"],["10","十/じゅう"],["100","百/ひゃく"],["1000","千/せん"],["10000","万/まん"],["First","第一/だいいち"],["Second","第二/だいに"],["Third","第三/だいさん"],["Half","半/はん"],["Few","少し/すこし"],["Many","多い/おおい"]],
 "Japanese Time & Date":[["Now","今/いま"],["Today","今日/きょう"],["Tomorrow","明日/あした"],["Yesterday","昨日/きのう"],["Morning","朝/あさ"],["Afternoon","昼/ひる"],["Evening","夕方/ゆうがた"],["Night","夜/よる"],["Week","週/しゅう"],["Month","月/つき・がつ"],["Year","年/とし・ねん"],["Minute","分/ふん・ぷん"],["Hour","時/じ"],["What time is it?","今何時ですか"],["At what time?","何時に"],["Weekend","週末/しゅうまつ"],["Holiday","祝日/しゅくじつ"],["Birthday","誕生日/たんじょうび"],["This week","今週/こんしゅう"],["Next week","来週/らいしゅう"]],
 "Japanese Days & Months":[["Monday","月曜日/げつようび"],["Tuesday","火曜日/かようび"],["Wednesday","水曜日/すいようび"],["Thursday","木曜日/もくようび"],["Friday","金曜日/きんようび"],["Saturday","土曜日/どようび"],["Sunday","日曜日/にちようび"],["January","一月/いちがつ"],["February","二月/にがつ"],["March","三月/さんがつ"],["April","四月/しがつ"],["May","五月/ごがつ"],["June","六月/ろくがつ"],["July","七月/しちがつ"],["August","八月/はちがつ"],["September","九月/くがつ"],["October","十月/じゅうがつ"],["November","十一月/じゅういちがつ"],["December","十二月/じゅうにがつ"],["Weekend","週末/しゅうまつ"]],
 "Japanese Directions":[["Left","左"],["Right","右"],["Straight","まっすぐ"],["North","北"],["South","南"],["East","東"],["West","西"],["Near","近い"],["Far","遠い"],["Next to","隣"],["Across from","向かい"],["Corner","角"],["Intersection","交差点"],["Traffic light","信号"],["Bridge","橋"],["Road","道"],["Street","通り"],["Map","地図"],["Lost","迷いました"],["Which way?","どっちですか"]],
 "Japanese Shopping":[["How much is this?","これはいくらですか"],["Expensive","高い"],["Cheap","安い"],["Discount","割引"],["Cash","現金"],["Credit card","クレジットカード"],["Receipt","レシート"],["Bag","袋"],["Try on","試着"],["Size","サイズ"],["Small","小さい"],["Medium","中"],["Large","大きい"],["Color","色"],["Exchange","交換"],["Return","返品"],["Sold out","売り切れ"],["New","新しい"],["Used","中古"],["Where is the register?","レジはどこですか"]],
 "Japanese Emergencies":[["Help","助けて"],["Call the police","警察を呼んでください"],["Call an ambulance","救急車を呼んでください"],["I’m lost","迷いました"],["I’m sick","具合が悪いです"],["I’m injured","けがをしました"],["Allergic to...","…にアレルギーがあります"],["Fire","火事"],["Hospital","病院"],["Pharmacy","薬局"],["Danger","危険"],["Safe","安全"],["Where is the embassy?","大使館はどこですか"],["Lost my passport","パスポートを失くしました"],["I was robbed","盗まれました"],["I need help","助けが必要です"],["Emergency exit","非常口"],["Earthquake","地震"],["Typhoon","台風"],["Shelter","避難所"]],
 "Japanese Weather":[["Weather","天気"],["Sunny","晴れ"],["Cloudy","曇り"],["Rainy","雨"],["Snowy","雪"],["Windy","風が強い"],["Hot","暑い"],["Cold","寒い"],["Humid","湿気が多い"],["Temperature","気温"],["Forecast","予報"],["Storm","嵐"],["Thunder","雷"],["Lightning","稲妻"],["Flood","洪水"],["Drought","干ばつ"],["Clear sky","快晴"],["Drizzle","霧雨"],["Fog","霧"],["Rainbow","虹"]],
 "Japanese Family":[["Family","家族"],["Father","父"],["Mother","母"],["Older brother","兄"],["Older sister","姉"],["Younger brother","弟"],["Younger sister","妹"],["Grandfather","祖父"],["Grandmother","祖母"],["Husband","夫"],["Wife","妻"],["Child","子供"],["Son","息子"],["Daughter","娘"],["Uncle","おじ"],["Aunt","おば"],["Cousin","いとこ"],["Relative","親戚"],["Parents","両親"],["Siblings","兄弟"]],
 "Japanese School & Work":[["School","学校"],["Teacher","先生"],["Student","学生"],["Class","授業"],["Exam","試験"],["Homework","宿題"],["Company","会社"],["Office","オフィス"],["Boss","上司"],["Colleague","同僚"],["Meeting","会議"],["Schedule","予定"],["Project","プロジェクト"],["Deadline","締切"],["Break","休憩"],["Salary","給料"],["Work from home","在宅勤務"],["Commute","通勤"],["Promotion","昇進"],["Resume","履歴書"]],
 "Japanese Common Verbs":[["To eat","食べる"],["To drink","飲む"],["To go","行く"],["To come","来る"],["To see","見る"],["To hear","聞く"],["To speak","話す"],["To read","読む"],["To write","書く"],["To buy","買う"],["To sell","売る"],["To make","作る"],["To use","使う"],["To meet","会う"],["To live","住む"],["To sleep","寝る"],["To wake","起きる"],["To work","働く"],["To study","勉強する"],["To play","遊ぶ"]],
 "Japanese Adjectives":[["Big","大きい"],["Small","小さい"],["New","新しい"],["Old","古い"],["Good","良い"],["Bad","悪い"],["Fast","速い"],["Slow","遅い"],["Expensive","高い"],["Cheap","安い"],["Easy","簡単"],["Difficult","難しい"],["Interesting","面白い"],["Boring","つまらない"],["Busy","忙しい"],["Free (time)","暇"],["Hot (object)","熱い"],["Cold (object)","冷たい"],["Kind","優しい"],["Scary","怖い"]],
 "Japanese Particles":[["は (topic)","主題"],["が (subject)","主語"],["を (object)","目的語"],["に (time/place)","時・場所"],["へ (direction)","方向"],["で (location/method)","場所・手段"],["と (and/with)","並列・共同"],["も (also)","同様"],["から (from)","起点"],["まで (to/until)","終点"],["より (than)","比較"],["や (A, B, etc.)","例示"],["の (possession)","所有"],["か (question)","疑問"],["ね (seeking agree.)","確認"],["よ (assertive)","断定"],["ぞ (emphasis)","強調"],["しか (only)","限定"],["だけ (only)","限定"],["こそ (emphasis)","強調"]],
 "Kanji N5 Set 1":[["日","sun/day"],["月","moon/month"],["火","fire"],["水","water"],["木","tree"],["金","gold/money"],["土","earth"],["山","mountain"],["川","river"],["田","rice field"],["人","person"],["口","mouth"],["目","eye"],["耳","ear"],["手","hand"],["足","foot"],["力","power"],["気","spirit"],["雨","rain"],["車","car"]],
 "Kanji N5 Set 2":[["学","study"],["校","school"],["先","previous"],["生","life/student"],["友","friend"],["本","book"],["文","sentence"],["字","character"],["間","interval"],["時","time"],["上","up"],["下","down"],["中","middle"],["大","big"],["小","small"],["長","long"],["高","tall/expensive"],["安","cheap/safe"],["新","new"],["古","old"]],
 "Kanji N5 Set 3":[["白","white"],["黒","black"],["赤","red"],["青","blue"],["色","color"],["早","early"],["行","go"],["来","come"],["帰","return"],["食","eat"],["飲","drink"],["見","see"],["聞","hear"],["話","speak"],["読","read"],["書","write"],["買","buy"],["売","sell"],["会","meet"],["住","live"]],
 "Kanji N5 Set 4":[["入","enter"],["出","exit"],["立","stand"],["座","sit"],["休","rest"],["何","what"],["名","name"],["年","year"],["先","ahead"],["今","now"],["午","noon"],["前","before"],["後","after"],["毎","every"],["半","half"],["分","minute"],["国","country"],["天","heaven"],["気","spirit"],["電","electric"]]
};

const pack = topics.map(name=>{
  const pairs = dict[name];
  if(pairs) return { title: name, name, cards: pairs.map(([q,a])=>({q, a})) };
  const cards=[]; for(let i=1;i<=20;i++) cards.push({q:`${name}: Item ${i}`, a:`${name} Answer ${i}`});
  return { title: name, name, cards };
});

fs.writeFileSync(out, JSON.stringify(pack,null,2));
console.log('Wrote', out, 'with', pack.length, 'topics and', pack.reduce((s,t)=>s+t.cards.length,0),'cards');
