const fs=require('fs'),p='app/data/flashcards.json';const d=JSON.parse(fs.readFileSync(p,'utf8'));const W=(t,c)=>{const i=(d.topics||[]).findIndex(x=>x.title===t);const cards=c.map(([q,a])=>({q,a}));if(i>=0)d.topics[i]={title:t,cards};else(d.topics||(d.topics=[])).push({title:t,cards})};

W("Operating Systems",[
["Kernel vs user space","Kernel has full privileges; user space is restricted"],
["System call","Interface for user apps to request kernel services"],
["Process states","New, ready, running, waiting, terminated"],
["Thread","Lightweight unit of execution within a process"],
["Context switch","CPU switches execution state between threads/processes"],
["Scheduling goal","Fairness, throughput, latency, utilization"],
["Preemptive vs cooperative","Kernel can interrupt vs threads yield voluntarily"],
["Mutex vs semaphore","Mutex single owner; semaphore counting resource"],
["Deadlock conditions","Mutual exclusion, hold and wait, no preemption, circular wait"],
["Virtual memory","Abstraction providing large contiguous address space"],
["Paging","Memory split into fixed-size pages/frames"],
["TLB","Cache of recent page table translations"],
["Copy-on-write","Defer copying until a write occurs"],
["File descriptor","Integer handle to open file/socket/pipe"],
["Inode","Metadata and block pointers for a file"],
["Memory map file","Map file into virtual memory for I/O"],
["Signal","Asynchronous notification to a process"],
["Fork vs exec","fork duplicates process; exec replaces image"],
["OOM killer","Selects and kills processes when memory is exhausted"],
["Swap","Move pages between RAM and disk"]
]);

W("Networking",[
["OSI layers","Physical, Data Link, Network, Transport, Session, Presentation, Application"],
["TCP vs UDP","Reliable stream vs best-effort datagrams"],
["TCP handshake","SYN → SYN-ACK → ACK"],
["TLS","Encrypts transport channel; provides confidentiality and integrity"],
["DNS","Resolves names to IP addresses"],
["CDN","Edge cache to reduce latency and origin load"],
["NAT","Map private addresses to public address"],
["Subnet mask","Defines network/host bits of an address"],
["CIDR example","192.168.1.0/24"],
["Routing vs switching","Between networks vs within a LAN"],
["BGP","Inter-domain routing protocol on the Internet"],
["HTTP/1.1 vs HTTP/2","Keep-alive vs multiplexed streams over one connection"],
["HTTP/3","Runs over QUIC/UDP with multiplexing and TLS by default"],
["Latency vs throughput","Delay vs data volume per unit time"],
["MTU","Maximum transmission unit for a link"],
["Packet loss","Triggers retransmission and reduces throughput"],
["WebSocket","Full-duplex TCP-based persistent connection"],
["HSTS","Forces HTTPS on a domain"],
["CORS","Controls cross-origin resource access from browsers"],
["Keep-alive","Reuses TCP connection for multiple requests"]
]);

W("Databases",[
["Relational vs NoSQL","Tables with schema vs key-value/document/column/graph"],
["ACID","Atomicity, Consistency, Isolation, Durability"],
["Primary key","Unique identifier for a row"],
["Foreign key","References primary key in another table"],
["Index purpose","Accelerate lookups by key/column"],
["B-tree index","Balanced tree enabling range scans"],
["Hash index","O(1) equality lookups; poor for ranges"],
["Normalization","Reduce redundancy and anomalies"],
["Transaction","Group of operations that commit or rollback together"],
["Isolation levels","Read uncommitted, read committed, repeatable read, serializable"],
["Deadlock","Transactions wait on each other in a cycle"],
["MVCC","Readers don’t block writers via versions"],
["Sharding","Horizontal partitioning across nodes"],
["Replication","Copy data to secondaries for HA/reads"],
["CAP theorem","Consistency, Availability, Partition tolerance; pick two in failure"],
["Eventual consistency","Replicas converge over time"],
["Query plan","Execution strategy chosen by optimizer"],
["OLTP vs OLAP","Transactional workloads vs analytical queries"],
["Star schema","Fact table with dimension tables"],
["CDC","Change data capture stream of mutations"]
]);

W("Web Development",[
["Semantic HTML","Meaningful elements like <article> <nav> <main>"],
["Flexbox","1D layout along main/cross axes"],
["CSS Grid","2D layout with rows and columns"],
["Responsive units","%, rem, vw, vh, minmax"],
["Accessibility","Labels, roles, focus order, contrast"],
["DOM","In-memory tree representation of the document"],
["SPA vs MPA","Client-side routing vs server-rendered pages"],
["SSR vs CSR","Server renders HTML vs browser renders"],
["Hydration","Attach event handlers to SSR HTML"],
["Bundlers","Vite, Webpack, esbuild, Parcel"],
["Transpilers","Babel, SWC"],
["Cookies vs localStorage","Cookies sent to server; localStorage stays client"],
["SameSite","Restrict cross-site cookie sending"],
["CSP","Content-Security-Policy to mitigate XSS"],
["Service worker","Background script for caching/offline"],
["PWA","Installable app-like web experience"],
["Debounce vs throttle","Delay after quiet period vs limit frequency"],
["Fetch","Promise-based HTTP API"],
["HTTP 201","Created"],
["ARIA role","role='button' to expose semantics"]
]);

W("Mobile Development",[
["Native vs cross-platform","Platform SDKs vs shared codebase"],
["React Native bridge","Binds JS to native modules"],
["Expo managed","Build without native Xcode/Gradle config"],
["Navigation","@react-navigation/native stacks/tabs/drawers"],
["State management","Redux, Zustand, Recoil"],
["Gesture handling","react-native-gesture-handler"],
["Animations","react-native-reanimated"],
["Offline storage","AsyncStorage and SQLite"],
["Push notifications","APNs/FCM integration"],
["Deep linking","Open screens via URL scheme"],
["App signing","Keystore/Certificates for release builds"],
["Permissions","Runtime prompts for camera/location/etc"],
["Profiling","Flipper/Perf monitors"],
["Bundle size control","Code split, image optimization"],
["OTA updates","EAS Updates deliver JS bundle"],
["EAS build","Cloud CI for iOS/Android"],
["Universal links","HTTP links to specific screens"],
["Sensors","Accelerometer, GPS, camera"],
["Layout system","Flexbox-based measure/layout"],
["Accessibility","Accessible components and labels"]
]);

W("Cybersecurity",[
["CIA triad","Confidentiality, Integrity, Availability"],
["Hashing vs encryption","One-way vs reversible with key"],
["Symmetric vs asymmetric","Same key vs key pair"],
["XSS","Inject and execute scripts in client"],
["CSRF","Trick browser into sending unwanted requests"],
["SQLi","Inject SQL via unsanitized inputs"],
["Clickjacking","Hidden frame overlays stealing clicks"],
["Password hashing","BCrypt, Argon2 with salt"],
["Salt purpose","Defeat rainbow tables and collisions"],
["MFA","Multiple factors increase security"],
["Zero trust","Never trust, always verify"],
["Least privilege","Grant minimum required access"],
["RBAC","Role-based permission model"],
["Secret management","Vault/KMS instead of env files"],
["Key rotation","Regularly replace and revoke keys"],
["Pen testing","Authorized simulated attacks"],
["Threat modeling","Identify assets, threats, mitigations"],
["Security headers","CSP, HSTS, X-Frame-Options"],
["SSRF","Server-side request forgery to internal services"],
["RCE","Remote code execution vulnerability"]
]);

W("Cloud Computing",[
["IaaS","Virtualized servers/network/storage"],
["PaaS","Managed runtimes/databases"],
["SaaS","Hosted full applications"],
["Region vs AZ","Geography vs isolated datacenters"],
["VPC","Isolated virtual network"],
["Load balancer","Distributes traffic across instances"],
["Auto scaling","Adjust instance count to demand"],
["Serverless","Managed compute per request"],
["Cold start","First invocation latency"],
["IAM","Identity and access policies"],
["Spot instances","Cheap preemptible compute"],
["IaC","Declarative infra code (Terraform)"],
["State locking","Prevent concurrent TF state edits"],
["Cost controls","Budgets, rightsizing, shutdown idle"],
["Reserved instances","Discount with commitment"],
["Multi-cloud","Run across providers"],
["Monitoring","Metrics, logs, tracing"],
["Object storage","Durable bucket storage"],
["Egress cost","Charges for data leaving provider"],
["KMS","Managed encryption keys"]
]);

W("DevOps",[
["CI","Automated integration and tests on commits"],
["CD","Continuous delivery/deployment to environments"],
["Pipeline stages","Build, test, scan, package, deploy"],
["GitFlow","Develop/feature/release/hotfix branches"],
["Trunk-based","Short-lived branches, frequent merges"],
["Feature flags","Toggle behavior without redeploy"],
["Artifacts","Versioned build outputs in registry"],
["Docker layers","Layered filesystem for caching"],
["Kubernetes pods","One or more containers sharing network/volumes"],
["Service vs deployment","Stable IP vs replica controller"],
["Ingress","HTTP routing into cluster"],
["Helm","Templated K8s release packaging"],
["Blue/green","Two prod envs; flip traffic"],
["Canary","Gradual rollout to subset of users"],
["Observability","Logs, metrics, traces for insight"],
["Runbooks","Operational step-by-steps"],
["SLOs/SLIs","Targets and measurements of reliability"],
["Postmortem","Blameless incident analysis"],
["ChatOps","Ops via chat integrations"],
["Secrets","Manage via Vault/KMS"]
]);

W("AI & Machine Learning",[
["Supervised learning","Train on labeled inputs and targets"],
["Unsupervised learning","Discover structure without labels"],
["Validation set","Tune hyperparameters"],
["Test set","Final evaluation of generalization"],
["Overfitting","Memorize training noise; poor generalization"],
["Regularization","Penalize complexity (L1/L2, dropout)"],
["Gradient descent","Update params by loss gradient"],
["Learning rate","Step size of updates"],
["Loss function","Quantifies error (MSE, cross-entropy)"],
["Precision","TP/(TP+FP)"],
["Recall","TP/(TP+FN)"],
["ROC AUC","Ranking quality across thresholds"],
["Feature scaling","Standardize/normalize features"],
["One-hot encoding","Binary vector per category"],
["Cross-validation","K-fold resampling method"],
["Bias-variance","Underfit vs overfit trade-off"],
["Confusion matrix","TP FP FN TN table"],
["Ensemble","Combine models (bagging/boosting)"],
["Activation examples","ReLU, sigmoid, tanh"],
["Embeddings","Dense vector representations"]
]);

W("Statistics",[
["Population","Entire group of interest"],
["Sample","Subset used to infer population"],
["Mean","Arithmetic average"],
["Median","Middle value"],
["Mode","Most frequent value"],
["Variance","Average squared deviation"],
["Standard deviation","Square root of variance"],
["Law of large numbers","Sample mean approaches true mean"],
["Central limit theorem","Sample means approx normal"],
["Z-score","Standardized value"],
["Confidence interval","Range likely containing parameter"],
["p-value","Probability of data if H0 true"],
["Type I error","False positive"],
["Type II error","False negative"],
["t-test","Compare two means"],
["ANOVA","Compare multiple means"],
["Correlation","Strength of linear relation"],
["Regression","Model relationship between variables"],
["Bayes’ theorem","P(A|B)=P(B|A)P(A)/P(B)"],
["Nonparametric tests","Do not assume distribution"]
]);

W("Software Design",[
["SOLID","SRP,OCP,LSP,ISP,DIP"],
["KISS","Prefer simple solutions"],
["DRY","Avoid duplication of logic"],
["YAGNI","Do not build until needed"],
["Cohesion","How focused module responsibilities are"],
["Coupling","Interdependence between modules"],
["Factory","Create objects via interface"],
["Singleton","Single instance; careful with globals"],
["Strategy","Swap algorithms via interface"],
["Observer","Publish/subscribe notifications"],
["Decorator","Wrap to add behavior"],
["Adapter","Translate one interface to another"],
["Facade","Simplified interface to subsystem"],
["Repository","Abstraction over data layer"],
["CQRS","Separate read and write models"],
["Event sourcing","State from event log"],
["Hexagonal","Ports/adapters isolate domain"],
["Clean architecture","Entities/use cases/adapters"],
["DDD","Model core domain with ubiquitous language"],
["Anti-corruption layer","Protect domain from legacy model"]
]);

W("Algorithms",[
["Big-O of binary search","O(log n)"],
["Merge sort complexity","O(n log n)"],
["Quick sort average","O(n log n)"],
["Quick sort worst","O(n^2)"],
["Stable sort example","Merge sort is stable"],
["Dijkstra constraint","Nonnegative edges"],
["A* advantage","Heuristic guides search"],
["Topological sort","Linearize DAG order"],
["Kruskal","Greedy MST using DSU"],
["Prim","Grow MST from a start node"],
["Dynamic programming","Optimal substructure and overlapping subproblems"],
["Greedy","Local optimum aiming for global"],
["Backtracking","Search with undo when invalid"],
["KMP","Linear-time substring search"],
["Sliding window","Two pointers over ranges"],
["Divide and conquer","Split, solve, combine"],
["Reservoir sampling","Random sample from stream"],
["Kadane","Max subarray sum in O(n)"],
["Bellman-Ford","Handles negative edges"],
["Floyd–Warshall","All-pairs shortest paths"]
]);

W("Data Structures",[
["Array","Contiguous memory; O(1) access"],
["Linked list","Nodes with next pointers; O(1) insert at head"],
["Stack","LIFO push/pop O(1)"],
["Queue","FIFO enqueue/dequeue O(1)"],
["Hash table","Average O(1) lookup/insert"],
["Binary tree","Nodes with ≤2 children"],
["BST","Left<root<right ordering"],
["Heap","Max/min at root, partial order"],
["Graph","Vertices and edges"],
["Trie","Prefix tree for strings"],
["Set","Unique elements"],
["Map","Key→value association"],
["Priority queue","Removes highest priority first"],
["Deque","Double-ended queue"],
["Union-Find","Disjoint set with union/find"],
["Balanced trees","AVL, Red-Black maintain O(log n)"],
["B-tree","Disk-friendly balanced tree"],
["Skip list","Layered linked lists for O(log n)"],
["LRU cache","Recency-based eviction"],
["Segment tree","Range query/update structure"]
]);

fs.writeFileSync(p,JSON.stringify(d,null,2));
console.log('topics',d.topics.length,'cards',d.topics.reduce((s,t)=>s+t.cards.length,0));
