-- Nova Tutoring Economy Phase 3A
-- Server-backed quiz quotas + daily perfect claims for signed-in users.
-- Run this ONCE in the Supabase SQL Editor.

begin;

create table if not exists public.economy_quiz_daily (
  user_id uuid not null references auth.users(id) on delete cascade,
  day_key date not null,
  regular_base_coins integer not null default 0 check (regular_base_coins >= 0),
  regular_actual_coins integer not null default 0 check (regular_actual_coins >= 0),
  perfect_base_coins integer not null default 0 check (perfect_base_coins >= 0),
  perfect_actual_coins integer not null default 0 check (perfect_actual_coins >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, day_key)
);

create table if not exists public.economy_quiz_topic_daily (
  user_id uuid not null references auth.users(id) on delete cascade,
  day_key date not null,
  topic_id text not null,
  regular_base_coins integer not null default 0 check (regular_base_coins >= 0),
  regular_actual_coins integer not null default 0 check (regular_actual_coins >= 0),
  perfect_claimed boolean not null default false,
  perfect_base_coins integer not null default 0 check (perfect_base_coins >= 0),
  perfect_actual_coins integer not null default 0 check (perfect_actual_coins >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, day_key, topic_id)
);

create table if not exists public.economy_reward_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  source text not null,
  topic_id text,
  base_coins integer not null default 0,
  bonus_coins integer not null default 0,
  actual_coins integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists economy_reward_events_user_created_idx
  on public.economy_reward_events (user_id, created_at desc);

alter table public.economy_quiz_daily enable row level security;
alter table public.economy_quiz_topic_daily enable row level security;
alter table public.economy_reward_events enable row level security;

-- The app does not write these tables directly. Authenticated users use the
-- SECURITY DEFINER functions below, which enforce the quota rules atomically.
revoke all on public.economy_quiz_daily from anon, authenticated;
revoke all on public.economy_quiz_topic_daily from anon, authenticated;
revoke all on public.economy_reward_events from anon, authenticated;

create or replace function public.nova_quiz_economy_status(
  p_topic_id text
)
returns table (
  day_key date,
  daily_base_coins_earned integer,
  daily_actual_coins_earned integer,
  topic_base_coins_earned integer,
  topic_actual_coins_earned integer,
  perfect_claimed boolean,
  perfect_base_coins_earned integer,
  perfect_actual_coins_earned integer,
  has_aetherwyrm boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_day date := (timezone('America/New_York', now()))::date;
  v_topic text;
  v_has_aether boolean := false;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  v_topic := regexp_replace(
    lower(trim(coalesce(p_topic_id, ''))),
    '[^a-z0-9_-]+',
    '_',
    'g'
  );

  v_topic := trim(both '_' from v_topic);
  if v_topic = '' then
    v_topic := 'unknown';
  end if;

  select coalesce(
    position('aetherwyrm' in lower(coalesce(p.purchases::text, ''))) > 0,
    false
  )
  into v_has_aether
  from public.profiles p
  where p.id = v_uid;

  v_has_aether := coalesce(v_has_aether, false);

  return query
  select
    v_day,
    coalesce(d.regular_base_coins, 0),
    coalesce(d.regular_actual_coins, 0),
    coalesce(t.regular_base_coins, 0),
    coalesce(t.regular_actual_coins, 0),
    coalesce(t.perfect_claimed, false),
    coalesce(d.perfect_base_coins, 0),
    coalesce(d.perfect_actual_coins, 0),
    v_has_aether
  from (select 1) seed
  left join public.economy_quiz_daily d
    on d.user_id = v_uid
   and d.day_key = v_day
  left join public.economy_quiz_topic_daily t
    on t.user_id = v_uid
   and t.day_key = v_day
   and t.topic_id = v_topic;
end;
$$;

create or replace function public.nova_claim_quiz_reward(
  p_topic_id text,
  p_kind text,
  p_event_key text
)
returns table (
  awarded boolean,
  reason text,
  base_coins integer,
  coins_awarded integer,
  daily_base_coins_earned integer,
  daily_actual_coins_earned integer,
  topic_base_coins_earned integer,
  topic_actual_coins_earned integer,
  perfect_claimed boolean,
  perfect_base_coins_earned integer,
  perfect_actual_coins_earned integer,
  has_aetherwyrm boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_day date := (timezone('America/New_York', now()))::date;
  v_topic text;
  v_kind text := lower(trim(coalesce(p_kind, '')));
  v_event_key text := trim(coalesce(p_event_key, ''));

  v_daily_base integer := 0;
  v_daily_actual integer := 0;
  v_topic_base integer := 0;
  v_topic_actual integer := 0;
  v_perfect_claimed boolean := false;
  v_perfect_base_total integer := 0;
  v_perfect_actual_total integer := 0;

  v_base integer := 0;
  v_bonus integer := 0;
  v_actual integer := 0;
  v_reason text := 'awarded';
  v_has_aether boolean := false;

  v_existing_base integer;
  v_existing_actual integer;
  v_existing_reason text;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if v_event_key = '' or length(v_event_key) > 220 then
    raise exception 'Invalid event key';
  end if;

  if v_kind not in ('correct', 'perfect') then
    raise exception 'Unsupported quiz reward kind: %', v_kind;
  end if;

  v_topic := regexp_replace(
    lower(trim(coalesce(p_topic_id, ''))),
    '[^a-z0-9_-]+',
    '_',
    'g'
  );
  v_topic := trim(both '_' from v_topic);
  if v_topic = '' then
    v_topic := 'unknown';
  end if;

  -- Detect Aetherwyrm from the signed-in user's persisted ownership mirror.
  -- For ordinary correct-answer and daily-perfect rewards, Aetherwyrm is the
  -- only Legendary that changes the coin amount.
  select coalesce(
    position('aetherwyrm' in lower(coalesce(p.purchases::text, ''))) > 0,
    false
  )
  into v_has_aether
  from public.profiles p
  where p.id = v_uid;

  v_has_aether := coalesce(v_has_aether, false);

  insert into public.economy_quiz_daily (
    user_id,
    day_key
  ) values (
    v_uid,
    v_day
  )
  on conflict (user_id, day_key) do nothing;

  insert into public.economy_quiz_topic_daily (
    user_id,
    day_key,
    topic_id
  ) values (
    v_uid,
    v_day,
    v_topic
  )
  on conflict (user_id, day_key, topic_id) do nothing;

  -- Idempotency: if the exact same event is retried, return the original award
  -- instead of paying it twice.
  select
    e.base_coins,
    e.actual_coins,
    coalesce(e.metadata->>'reason', 'duplicate')
  into
    v_existing_base,
    v_existing_actual,
    v_existing_reason
  from public.economy_reward_events e
  where e.user_id = v_uid
    and e.event_key = v_event_key;

  if found then
    select
      d.regular_base_coins,
      d.regular_actual_coins,
      d.perfect_base_coins,
      d.perfect_actual_coins
    into
      v_daily_base,
      v_daily_actual,
      v_perfect_base_total,
      v_perfect_actual_total
    from public.economy_quiz_daily d
    where d.user_id = v_uid
      and d.day_key = v_day;

    select
      t.regular_base_coins,
      t.regular_actual_coins,
      t.perfect_claimed
    into
      v_topic_base,
      v_topic_actual,
      v_perfect_claimed
    from public.economy_quiz_topic_daily t
    where t.user_id = v_uid
      and t.day_key = v_day
      and t.topic_id = v_topic;

    return query select
      v_existing_actual > 0,
      'duplicate',
      coalesce(v_existing_base, 0),
      coalesce(v_existing_actual, 0),
      coalesce(v_daily_base, 0),
      coalesce(v_daily_actual, 0),
      coalesce(v_topic_base, 0),
      coalesce(v_topic_actual, 0),
      coalesce(v_perfect_claimed, false),
      coalesce(v_perfect_base_total, 0),
      coalesce(v_perfect_actual_total, 0),
      v_has_aether;
    return;
  end if;

  -- Lock today's rows so two devices cannot race the counters.
  select
    d.regular_base_coins,
    d.regular_actual_coins,
    d.perfect_base_coins,
    d.perfect_actual_coins
  into
    v_daily_base,
    v_daily_actual,
    v_perfect_base_total,
    v_perfect_actual_total
  from public.economy_quiz_daily d
  where d.user_id = v_uid
    and d.day_key = v_day
  for update;

  select
    t.regular_base_coins,
    t.regular_actual_coins,
    t.perfect_claimed
  into
    v_topic_base,
    v_topic_actual,
    v_perfect_claimed
  from public.economy_quiz_topic_daily t
  where t.user_id = v_uid
    and t.day_key = v_day
    and t.topic_id = v_topic
  for update;

  if v_kind = 'correct' then
    if v_daily_base >= 500 then
      v_reason := 'daily_limit';
    elsif v_topic_base >= 100 then
      v_reason := 'topic_limit';
    else
      v_base := least(
        5,
        500 - v_daily_base,
        100 - v_topic_base
      );

      v_bonus := case
        when v_has_aether then round(v_base * 0.20)::integer
        else 0
      end;

      v_actual := v_base + v_bonus;

      update public.economy_quiz_daily
      set
        regular_base_coins = regular_base_coins + v_base,
        regular_actual_coins = regular_actual_coins + v_actual,
        updated_at = now()
      where user_id = v_uid
        and day_key = v_day;

      update public.economy_quiz_topic_daily
      set
        regular_base_coins = regular_base_coins + v_base,
        regular_actual_coins = regular_actual_coins + v_actual,
        updated_at = now()
      where user_id = v_uid
        and day_key = v_day
        and topic_id = v_topic;

      v_daily_base := v_daily_base + v_base;
      v_daily_actual := v_daily_actual + v_actual;
      v_topic_base := v_topic_base + v_base;
      v_topic_actual := v_topic_actual + v_actual;
    end if;

  elsif v_kind = 'perfect' then
    if v_perfect_claimed then
      v_reason := 'perfect_claimed';
    else
      v_base := 50;
      v_bonus := case
        when v_has_aether then round(v_base * 0.20)::integer
        else 0
      end;
      v_actual := v_base + v_bonus;

      update public.economy_quiz_daily
      set
        perfect_base_coins = perfect_base_coins + v_base,
        perfect_actual_coins = perfect_actual_coins + v_actual,
        updated_at = now()
      where user_id = v_uid
        and day_key = v_day;

      update public.economy_quiz_topic_daily
      set
        perfect_claimed = true,
        perfect_base_coins = v_base,
        perfect_actual_coins = v_actual,
        updated_at = now()
      where user_id = v_uid
        and day_key = v_day
        and topic_id = v_topic;

      v_perfect_claimed := true;
      v_perfect_base_total := v_perfect_base_total + v_base;
      v_perfect_actual_total := v_perfect_actual_total + v_actual;
    end if;
  end if;

  if v_actual > 0 then
    update public.profiles
    set
      coins = coalesce(coins, 0) + v_actual,
      updated_at = now()
    where id = v_uid;

    if not found then
      raise exception 'Profile row not found for authenticated user';
    end if;
  end if;

  insert into public.economy_reward_events (
    user_id,
    event_key,
    source,
    topic_id,
    base_coins,
    bonus_coins,
    actual_coins,
    metadata
  ) values (
    v_uid,
    v_event_key,
    case when v_kind = 'correct'
      then 'quiz_correct'
      else 'quiz_daily_perfect_bonus'
    end,
    v_topic,
    v_base,
    v_bonus,
    v_actual,
    jsonb_build_object(
      'reason', v_reason,
      'dayKey', v_day,
      'aetherwyrm', v_has_aether,
      'serverEconomyVersion', 3
    )
  );

  return query select
    v_actual > 0,
    v_reason,
    v_base,
    v_actual,
    v_daily_base,
    v_daily_actual,
    v_topic_base,
    v_topic_actual,
    v_perfect_claimed,
    v_perfect_base_total,
    v_perfect_actual_total,
    v_has_aether;
end;
$$;

revoke all on function public.nova_quiz_economy_status(text) from public;
revoke all on function public.nova_claim_quiz_reward(text, text, text) from public;

grant execute on function public.nova_quiz_economy_status(text) to authenticated;
grant execute on function public.nova_claim_quiz_reward(text, text, text) to authenticated;

commit;
