/**
 * AUTO-GENERATED by scripts/generate-sku-map.mjs
 * Source: app/_lib/catalog.ts
 * Found 34 catalog items; matched 33.
 * Edit SKU_TO_PRODUCT_ID manually if any are incorrect.
 */

export const STRIPE_PRODUCT_IDS = [
  "prod_TFfaQGrHAvDqbL",
  "prod_TFcQwzMyW4yv64",
  "prod_TFcOzn4jw88sa6",
  "prod_TFcNNFrRJeDNdU",
  "prod_TFcJPHAdrXTh0g",
  "prod_TFcHktEuWuJtoU",
  "prod_TFQFvhM9kmYlQt",
  "prod_TEJSSAWhQVWjMy",
  "prod_TEJRAKUFgXjmpM",
  "prod_TEJRPU7nXAN1eJ",
  "prod_TEJPC8HIdX4MFP",
  "prod_TEJOLtH9hWcwqU",
  "prod_TEJNONMFOilNln",
  "prod_TEJMNCYpZmWd4G",
  "prod_TEJLpEhIzTFX69",
  "prod_TEJGuE1QYi7lpF",
  "prod_TEJFaqzUqA8g36",
  "prod_TEJEQuKVJFpMQ9",
  "prod_TEJCsJyyB6GDOQ",
  "prod_TEJ3nQpbnxBc8v",
  "prod_TEJ3Zx5MWLv9tV",
  "prod_TEIyhPxZRyjm15",
  "prod_TEIuLi7S5r8YKb",
  "prod_TEIs23HG5KHFCp",
  "prod_TEIqazLNftnz4j",
  "prod_TEIpv64N52FpdT",
  "prod_TEIokf5jy2rFFd",
  "prod_TEIoLX524g5bUk",
  "prod_TEImuiJcIEerXG",
  "prod_TEIl17OQhITvGP",
  "prod_TEIj5rSF62hp5b",
  "prod_TEIhSDjINHWg7U",
  "prod_TEIgC6JmU2ALTh",
  "prod_TEIeuYnCTjKtqU",
  "prod_TEIbGbdViXLjnW",
  "prod_TEIZRXrtjvfBo9",
  "prod_TEIXJLlS8YHGPQ"
] as const;

type Sku = [
  "plushie_nova_pajamas",
  "plushie_bunny_classic",
  "plushie_bunny_white",
  "plushie_star",
  "plushie_bunny_book",
  "plushie_devil",
  "plushie_purple",
  "tee_nova_glow",
  "hoodie_nova",
  "beanie_nova",
  "pajamas",
  "pajama_bottoms",
  "sweat_bottoms",
  "hat",
  "keychain_nova",
  "stationery_set",
  "phone_case",
  "cursor_glow",
  "cursor_orb",
  "cursor_star_trail",
  "theme_neon",
  "theme:starry",
  "theme_pink",
  "theme_dark",
  "theme_mint",
  "theme_glitter",
  "theme_black_gold",
  "theme_crimson_dream",
  "theme_emerald_wave",
  "theme_neon_purple",
  "theme_silver_frost",
  "bundle_neon",
  "pack_1k",
  "pack_5k"
][number];

export const SKU_TO_PRODUCT_ID: Partial<Record<Sku, string>> = {
  "plushie_nova_pajamas": "prod_TFQFvhM9kmYlQt", // ✔ Nova Plushie (Pajamas) → Nova Plushie (Pajamas) (score 1.15)
  "plushie_bunny_classic": "prod_TFcOzn4jw88sa6", // ✔ Bunny Plushie (Classic) → Bunny Plushie (Black) (score 0.5)
  "plushie_bunny_white": "prod_TEJCsJyyB6GDOQ", // ✔ Bunny Plushie (White) → Bunny Plushie (White) (score 1.15)
  "plushie_star": "prod_TEIXJLlS8YHGPQ", // ✔ Star Plushie → Star Plushie (score 1.15)
  "plushie_bunny_book": "prod_TEJEQuKVJFpMQ9", // ✔ Bunny Plushie (Book) → Bunny Plushie (Book) (score 1.15)
  "plushie_devil": "prod_TEJFaqzUqA8g36", // ✔ Nova Plushie Devil → Nova Plushie Devil (score 1.15)
  "plushie_purple": "prod_TEJGuE1QYi7lpF", // ✔ Nova Plushie Purple → Nova Plushie Purple (score 1.15)
  "tee_nova_glow": "prod_TFcJPHAdrXTh0g", // ✔ Nova Glow Tee → Nova Glow Tee (score 1.15)
  "hoodie_nova": "prod_TEIbGbdViXLjnW", // ✔ Nova Hoodie → Nova Hoodie (score 1.15)
  "beanie_nova": "prod_TEIZRXrtjvfBo9", // ✔ Nova Beanie → Nova Beanie (score 1.15)
  "pajamas": "prod_TFcQwzMyW4yv64", // ✔ Pajamas (Set) → Pajamas (Set) (score 1.15)
  // "pajama_bottoms": "prod_...", // TODO: Pajama Bottoms (no confident match; score 0.333)
  "sweat_bottoms": "prod_TEIeuYnCTjKtqU", // ✔ Sweat Bottoms → Sweat Bottoms (score 1.15)
  "hat": "prod_TEIl17OQhITvGP", // ✔ Hat → Hat (score 1.15)
  "keychain_nova": "prod_TEIhSDjINHWg7U", // ✔ Nova Keychain → Nova Keychain (score 1.15)
  "stationery_set": "prod_TEImuiJcIEerXG", // ✔ Stationery Set → Stationery Set (score 1.15)
  "phone_case": "prod_TEIj5rSF62hp5b", // ✔ Phone Case → Phone Case (score 1.15)
  "cursor_glow": "prod_TEJ3Zx5MWLv9tV", // ✔ Cursor: Glow → Cursor — Glow (score 0.667)
  "cursor_orb": "prod_TEJ3nQpbnxBc8v", // ✔ Cursor: Orb Glow → Cursor — Orb (score 0.5)
  "cursor_star_trail": "prod_TEIyhPxZRyjm15", // ✔ Cursor: Star Trail → Cursor — Star (score 0.5)
  "theme_neon": "prod_TEJOLtH9hWcwqU", // ✔ Theme: Neon Nova → Theme: Neon Nova (score 1.15)
  "theme:starry": "prod_TEJPC8HIdX4MFP", // ✔ Theme: Starry Night → Theme: Starry Night (score 1.15)
  "theme_pink": "prod_TEJRPU7nXAN1eJ", // ✔ Theme: Pink Dawn → Theme: Pink Dawn (score 1.15)
  "theme_dark": "prod_TEJSSAWhQVWjMy", // ✔ Theme: Dark Nova → Theme: Dark Nova (score 1.15)
  "theme_mint": "prod_TEJRAKUFgXjmpM", // ✔ Theme: Mint Breeze → Theme: Mint Breeze (score 1.15)
  "theme_glitter": "prod_TFcHktEuWuJtoU", // ✔ Theme: Glitter → Theme: Glitter (score 1.15)
  "theme_black_gold": "prod_TEIokf5jy2rFFd", // ✔ Theme: Black & Gold → theme_black_gold (score 0.75)
  "theme_crimson_dream": "prod_TEIpv64N52FpdT", // ✔ Theme: Crimson Dream → Theme — Crimson Dream (score 0.75)
  "theme_emerald_wave": "prod_TEIqazLNftnz4j", // ✔ Theme: Emerald Wave → Theme — Emerald Wave (score 0.75)
  "theme_neon_purple": "prod_TEIoLX524g5bUk", // ✔ Theme: Neon Purple → Theme — Neon Purple (score 0.75)
  "theme_silver_frost": "prod_TEIs23HG5KHFCp", // ✔ Theme: Silver Frost → Theme — Silver Frost (score 0.75)
  "bundle_neon": "prod_TEJLpEhIzTFX69", // ✔ Neon Starter Bundle → Neon Starter Bundle (score 1.15)
  "pack_1k": "prod_TEJMNCYpZmWd4G", // ✔ 1,000 coins → 1,000 coins (score 1.4)
  "pack_5k": "prod_TEJNONMFOilNln", // ✔ 5,000 coins → 5,000 coins (score 1.4)
};

export function resolveProductIdForSku(sku?: string | null): string | null {
  if (!sku) return null;
  const id = (SKU_TO_PRODUCT_ID as any)[sku];
  return typeof id === "string" && id.startsWith("prod_") ? id : null;
}
